import Autoform.SpecsGen.Basis
import Autoform.Harness.Audit
import Autoform.Generated.V8Base

/-! Generated by `scripts/synth_specs.py`. Do not edit by hand. -/
namespace Autoform.SpecsGen.V8Base.Base

open Autoform.Core Autoform.Refine Autoform.SpecsGen

-- The proofs below are by computation on concrete inputs: the kernel walks the
-- interpreter, and deeply nested calls need more than the default budgets.
set_option maxRecDepth 20000
set_option maxHeartbeats 1000000

abbrev P : Program := Autoform.Generated.V8Base.program

/-- The module-initialiser heap, evaluated once by `initGlobals P 5000 moduleInits` and
frozen into this literal so that the kernel does not re-run the initialisers for every
case of every proof. -/
def h0 : Heap := [{ cls := "<globals>", fields := [], captured := [] }]

/-- Address of the globals frame. -/
def gref : Ref := 0
def base : Nat := h0.length
def C : Ctx := { dialect := P.dialect, table := P.table, globals := gref }
def FUEL : Nat := 400
open Autoform.Generated.V8Base

/-- Every function body reachable in this program is `tryFinally`-free, so
`Autoform/FuelMono.lean`'s monotonicity theorems apply to this context. Checked by
computation over the whole function table, not assumed. `Stmt.tryFinally` is the single
construct that breaks fuel monotonicity (`FuelMono.tryFinally_breaks_fuel_mono` exhibits a
program answering 1 at fuel 4 and 2 at fuel 5), so this is the hypothesis that decides
whether a law checked at one budget holds at every larger one. -/
theorem C_tfFree : TFFreeCtx C := by
  refine tfFree_of_table ?_
  have h : (C.table.all fun p => tfFreeS p.2.body) = true := by rfl
  exact fun p hp => (List.all_eq_true.mp h) p hp


/-!
# Synthesized specifications — `V8Base`

**Generated by `scripts/synth_specs.py`. Do not edit by hand.**

Every statement below is about `Autoform/Generated/V8Base.lean` *by import*, so a
mutation of the generated module is a mutation of the subject of these theorems
(`scripts/mutate.py --spec-file`). The `#audit_depends` block at the end fails the build
for any theorem that does not mention the implementation it claims to constrain.

What each family claims, in the order of `STRATEGY.md` §4:

* `conform_*` (§4.4, cross-implementation) — the interpreter reproduces, case by case,
  the outcome **CPython** produced when the repository's own test suite called this
  function. The right-hand sides were recorded by `scripts/differential.py`'s trace hook;
  they are not this system's own output, which is what keeps the family from being an
  elaborate `rfl`.
* `runs_*` / `returns_*` (§4.2, structural) — on this domain the interpreter neither
  reaches an untranslated construct nor exhausts its fuel. `EResult` distinguishes
  `.hole` and `.outOfFuel` from behaviour, so this is a real property, and it is stated
  only for functions whose AST *could* violate it.
* `heappure_*`, `const_*`, `projects_*`, `identity_*`, `idempotent_*`, `involutive_*`,
  `commutes_*`, `nonneg_*` (§4.3, algebraic) — laws mined from observed executions and
  **refuted against a fuzzed domain before emission**. Survivors only.
* `uconst_*`, `uproj_*` — universally quantified refinements, proved for every input and
  every fuel budget above a stated bound.

Domains are finite and explicit, and the theorems about them are proved by computation.
That is deliberate: a kernel-checked test is a test whose axiom basis is auditable and
whose subject a mutation gate can attack.

**Fuel.** A law checked at one budget is a weaker claim than it looks, so each law here is
stated as `∀ fuel, FUEL ≤ fuel → …` wherever that could be *proved*: checked at `FUEL` by
computation and transported by `Autoform/FuelMono.lean`'s `applyFunc_fuel_mono`. That
transport needs two side conditions, both discharged rather than assumed — the context is
`tryFinally`-free (`C_tfFree`, by computation over the function table) and the run did not
end in `outOfFuel` (the `g…` guard, evaluated over the same domain as the law). Where
either fails, the theorem stays at `FUEL` and its generalization is recorded in
`obligations` below as a `Prop`-valued `def` — a statement, not an admission.

There is no `sorry` in this file.

Counts for this run are in `Autoform/SpecsGen/report.json`.
-/

def dom_runs_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-21249), Val.int (-9223372036854775511)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (6125780340178803969)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-8035)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775797), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (-2)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854765614), Val.int (-300)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (-9223372036854773702)] }]

def dom_returns_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-21249), Val.int (-9223372036854775511)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (6125780340178803969)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-8035)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775797), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (-2)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854765614), Val.int (-300)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (-9223372036854773702)] }]

def dom_runs_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (74), Val.int (-9223372036854749573)] },
   { heap := h0 ++ [], self := none, args := [Val.int (6125780340178803969), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (-1842855630749095363)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-31333)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (28367)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-4370), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8155596544368608066), Val.int (-9223372036854748347)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (2097065261283699244)] }]

def dom_returns_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (74), Val.int (-9223372036854749573)] },
   { heap := h0 ++ [], self := none, args := [Val.int (6125780340178803969), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (-1842855630749095363)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-31333)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (28367)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-4370), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8155596544368608066), Val.int (-9223372036854748347)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (2097065261283699244)] }]

def dom_idempotent_v8_base_SetPrintStackTrace_void_void : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "_\u0095\u001c;\u00b8"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-27237)] },
   { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775808)] },
   { heap := h0 ++ [], self := none, args := [Val.str "}Mj\u192f\u1d19\u1c74\u21f5\u00af"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00b2\u00be\u0086\u00b1\u29cba\u00f6"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-1886002477)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00df\u0088\u1119["] }]

def dom_idempotent_v8_base_SetFatalFunction_void_void : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "A\u12e1[~\u00a7\u0002H("] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854730841)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-7)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854775797)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u1ab0k1\u00e4Z\u1d37\u00fdI"] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (127)]] },
   { heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139)] }]

def dom_idempotent_v8_base_PosixInitializeCommon_void_char : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-7)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-30192)]] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036559664159)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "l?\u00ad\u00a2"] },
   { heap := h0 ++ [], self := none, args := [Val.int (2698)] },
   { heap := h0 ++ [], self := none, args := [Val.int (3021723606400056615)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-20836)] }]

def dom_runs_v8_base_OS_Initialize_duplicate_0_void_char : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u2a8d"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-30093607959703112948291903580161756742)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u2ac6\u0000\u00d2\u00f1%\u00f2\u001b\u05f9"] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854746682)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8035)] }]

def dom_returns_v8_base_OS_Initialize_duplicate_0_void_char : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u2a8d"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-30093607959703112948291903580161756742)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u2ac6\u0000\u00d2\u00f1%\u00f2\u001b\u05f9"] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854746682)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8035)] }]

def dom_idempotent_v8_base_OS_Initialize_duplicate_0_void_char : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u2a8d"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-30093607959703112948291903580161756742)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u2ac6\u0000\u00d2\u00f1%\u00f2\u001b\u05f9"] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854746682)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8035)] }]

def dom_heappure_v8_base_AddressRegion___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.list [Val.int (-5815782740631448771)], Val.str "\nAz\u008a\u2df3"] },
   { heap := h0 ++ [], self := none, args := [Val.bool false, Val.int (-9052)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00bf\u00b9\u00e6", Val.int (-9223372036854740054)] },
   { heap := h0 ++ [], self := none, args := [Val.str "cases", Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u0f1b\u0013\u2d9e\u00c7\u09a9\u0c56[\u282c", Val.int (130)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2097065261283699244), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854731939)], Val.int (-26161)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (8012993533289937693)] }]

def dom_idempotent_v8_base_AddressRegion___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.list [Val.int (-5815782740631448771)], Val.str "\nAz\u008a\u2df3"] },
   { heap := h0 ++ [], self := none, args := [Val.bool false, Val.int (-9052)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00bf\u00b9\u00e6", Val.int (-9223372036854740054)] },
   { heap := h0 ++ [], self := none, args := [Val.str "cases", Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u0f1b\u0013\u2d9e\u00c7\u09a9\u0c56[\u282c", Val.int (130)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2097065261283699244), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854731939)], Val.int (-26161)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (8012993533289937693)] }]

def dom_commutes_v8_base_AddressRegion___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.list [Val.int (-5815782740631448771)], Val.str "\nAz\u008a\u2df3"] },
   { heap := h0 ++ [], self := none, args := [Val.bool false, Val.int (-9052)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00bf\u00b9\u00e6", Val.int (-9223372036854740054)] },
   { heap := h0 ++ [], self := none, args := [Val.str "cases", Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u0f1b\u0013\u2d9e\u00c7\u09a9\u0c56[\u282c", Val.int (130)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2097065261283699244), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854731939)], Val.int (-26161)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (8012993533289937693)] }]

def dom_heappure_v8_base_AddressRegion___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "\u00f2", Val.int (82)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00c0\u00eb7\u000c", Val.str "\u00c5Ng\u00a7\u00d6\u00e6E"] },
   { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1000000000000000000)], Val.str "6\u00f4\u2e48"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u009c\u00c5", Val.int (-9223372036854775701)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854713668), Val.int (-25637)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9052), Val.int (23474)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769302), Val.int (1)] }]

def dom_idempotent_v8_base_AddressRegion___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "\u00f2", Val.int (82)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00c0\u00eb7\u000c", Val.str "\u00c5Ng\u00a7\u00d6\u00e6E"] },
   { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1000000000000000000)], Val.str "6\u00f4\u2e48"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u009c\u00c5", Val.int (-9223372036854775701)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854713668), Val.int (-25637)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9052), Val.int (23474)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769302), Val.int (1)] }]

def dom_commutes_v8_base_AddressRegion___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "\u00f2", Val.int (82)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00c0\u00eb7\u000c", Val.str "\u00c5Ng\u00a7\u00d6\u00e6E"] },
   { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1000000000000000000)], Val.str "6\u00f4\u2e48"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u009c\u00c5", Val.int (-9223372036854775701)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854713668), Val.int (-25637)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9052), Val.int (23474)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769302), Val.int (1)] }]

def dom_runs_v8_UnsignedDiv32_uint32_t_uint32_t_uint32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-31152), Val.int (-3032)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-30501), Val.int (-23786)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8035), Val.int (11)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (8012993533289937693)] },
   { heap := h0 ++ [], self := none, args := [Val.int (82), Val.int (-1738374194401833935)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (26614)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9052), Val.int (-9223372036854748347)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181), Val.int (8155596544368608066)] }]

def dom_returns_v8_UnsignedDiv32_uint32_t_uint32_t_uint32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-31152), Val.int (-3032)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-30501), Val.int (-23786)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8035), Val.int (11)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (8012993533289937693)] },
   { heap := h0 ++ [], self := none, args := [Val.int (82), Val.int (-1738374194401833935)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (26614)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9052), Val.int (-9223372036854748347)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181), Val.int (8155596544368608066)] }]

def dom_runs_v8_UnsignedDiv64_uint64_t_uint64_t_uint64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-7), Val.int (130)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833), Val.int (-20706)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854729933), Val.int (1)] },
   { heap := h0 ++ [], self := none, args := [Val.int (22762), Val.int (8320)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492), Val.int (22286)] },
   { heap := h0 ++ [], self := none, args := [Val.int (11), Val.int (25087)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8951265655611708266), Val.int (7144)] },
   { heap := h0 ++ [], self := none, args := [Val.int (65536), Val.int (-8035)] }]

def dom_returns_v8_UnsignedDiv64_uint64_t_uint64_t_uint64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-7), Val.int (130)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833), Val.int (-20706)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854729933), Val.int (1)] },
   { heap := h0 ++ [], self := none, args := [Val.int (22762), Val.int (8320)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492), Val.int (22286)] },
   { heap := h0 ++ [], self := none, args := [Val.int (11), Val.int (25087)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8951265655611708266), Val.int (7144)] },
   { heap := h0 ++ [], self := none, args := [Val.int (65536), Val.int (-8035)] }]

def dom_runs_v8_UnsignedMod32_uint32_t_uint32_t_uint32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-21249)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (50)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769302), Val.int (5626624876551845293)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2147483647), Val.int (3021723606400056615)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-114), Val.int (-9223372036854759946)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139), Val.int (-8951265655611708266)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-21555), Val.int (-25637)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2147483647), Val.int (-9223372033174926866)] }]

def dom_returns_v8_UnsignedMod32_uint32_t_uint32_t_uint32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-21249)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (50)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769302), Val.int (5626624876551845293)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2147483647), Val.int (3021723606400056615)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-114), Val.int (-9223372036854759946)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139), Val.int (-8951265655611708266)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-21555), Val.int (-25637)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2147483647), Val.int (-9223372033174926866)] }]

def dom_runs_v8_UnsignedMod64_uint64_t_uint64_t_uint64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (7696070463740520648), Val.int (22286)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748136), Val.int (-9223372036854748540)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086), Val.int (-8951265655611708266)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8683), Val.int (13179)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (5626624876551845293)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (31710)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854713668), Val.int (-9223372036854719199)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (300000)] }]

def dom_returns_v8_UnsignedMod64_uint64_t_uint64_t_uint64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (7696070463740520648), Val.int (22286)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748136), Val.int (-9223372036854748540)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086), Val.int (-8951265655611708266)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-8683), Val.int (13179)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (5626624876551845293)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (31710)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854713668), Val.int (-9223372036854719199)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (300000)] }]

def dom_runs_v8_WraparoundAdd32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-20706), Val.int (-30093607959703112948291903580161756742)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769961), Val.int (-21249)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (-9223372033281947594)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-2), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-644277784176366389), Val.int (-2147483648)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (7696070463740520648)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854738979)] }]

def dom_returns_v8_WraparoundAdd32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-20706), Val.int (-30093607959703112948291903580161756742)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769961), Val.int (-21249)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (-9223372033281947594)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-2), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-644277784176366389), Val.int (-2147483648)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (7696070463740520648)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854738979)] }]

def dom_commutes_v8_WraparoundAdd32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-20706), Val.int (-30093607959703112948291903580161756742)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769961), Val.int (-21249)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (-9223372033281947594)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-2), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-644277784176366389), Val.int (-2147483648)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (7696070463740520648)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854738979)] }]

def dom_heappure_v8_base_Hasher___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (400)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2843)] },
   { heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775807)] },
   { heap := h0 ++ [], self := none, args := [Val.str "6\u00f4\u2e48"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9324)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-2)] }]

def dom_idempotent_v8_base_Hasher___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (400)] },
   { heap := h0 ++ [], self := none, args := [Val.int (2843)] },
   { heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775807)] },
   { heap := h0 ++ [], self := none, args := [Val.str "6\u00f4\u2e48"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9324)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-2)] }]

def dom_heappure_v8_base_Hasher___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "\u0006\u00a1o\u00ff"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00d3El\u1161\u0086J\u00af\u1761"] },
   { heap := h0 ++ [], self := none, args := [Val.str "<\u1dd5"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u13d4Z"] },
   { heap := h0 ++ [], self := none, args := [Val.str ")Y\u0004\u00ed\u00e40\u00a5\u2197"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854775808)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "6\u00f4\u2e48"] }]

def dom_idempotent_v8_base_Hasher___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.str "\u0006\u00a1o\u00ff"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00d3El\u1161\u0086J\u00af\u1761"] },
   { heap := h0 ++ [], self := none, args := [Val.str "<\u1dd5"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u13d4Z"] },
   { heap := h0 ++ [], self := none, args := [Val.str ")Y\u0004\u00ed\u00e40\u00a5\u2197"] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854775808)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "6\u00f4\u2e48"] }]

def dom_runs_v8_base_hash64_uint64_t_uint64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724594)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5626624876551845293)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767578)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9324)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775645)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-27237)] }]

def dom_returns_v8_base_hash64_uint64_t_uint64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724594)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5626624876551845293)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767578)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9324)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775645)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-27237)] }]

def dom_runs_v8_base_hash32_uint32_t_uint32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (12)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-124)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.int (3130535145585281007)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-7)] }]

def dom_returns_v8_base_hash32_uint32_t_uint32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (12)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-124)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.int (3130535145585281007)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-7)] }]

def dom_idempotent_v8_base_hash_value_size_t_unsigned_char : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372033281947594)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9324)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8118)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-7)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854746682)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854721555)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036384244755)] }]

def dom_idempotent_v8_base_hash_value_size_t_shortunsigned : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-300)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (0)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854773788)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854749573)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23563)] },
   { heap := h0 ++ [], self := none, args := [Val.int (4294967296)] }]

def dom_identity_v8_base_internal_MakeStrictNum_StrictNumeric_T : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767797)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-27237)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8580004217855970090)] },
   { heap := h0 ++ [], self := none, args := [Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-26161)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139)] }]

def dom_idempotent_v8_base_internal_MakeStrictNum_StrictNumeric_T : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767797)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-27237)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8580004217855970090)] },
   { heap := h0 ++ [], self := none, args := [Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-26161)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139)] }]

def dom_involutive_v8_base_internal_MakeStrictNum_StrictNumeric_T : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.bool false] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767797)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-27237)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8580004217855970090)] },
   { heap := h0 ++ [], self := none, args := [Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-26161)] },
   { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139)] }]

def dom_heappure_v8_base_internal_RangeCheck___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-95), Val.str "\u00bc\u00e8"] },
   { heap := h0 ++ [], self := none, args := [Val.bool true, Val.int (-20706)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-25564), Val.int (-22947)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775701), Val.int (31710)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775029), Val.list [Val.int (12)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-74), Val.bool true] }]

def dom_idempotent_v8_base_internal_RangeCheck___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-95), Val.str "\u00bc\u00e8"] },
   { heap := h0 ++ [], self := none, args := [Val.bool true, Val.int (-20706)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-25564), Val.int (-22947)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775701), Val.int (31710)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775029), Val.list [Val.int (12)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-74), Val.bool true] }]

def dom_commutes_v8_base_internal_RangeCheck___init : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-95), Val.str "\u00bc\u00e8"] },
   { heap := h0 ++ [], self := none, args := [Val.bool true, Val.int (-20706)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-25564), Val.int (-22947)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775701), Val.int (31710)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775029), Val.list [Val.int (12)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-74), Val.bool true] }]

def dom_heappure_v8_base_internal_RangeCheck___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854754471), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00e0\u00fd", Val.list [Val.int (2698)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00f9e", Val.int (-5815782740631448771)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (5884099853687727139)], Val.int (-14522)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775651), Val.str "]#_\u0010"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u0002\u0007", Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854729933), Val.int (400)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23), Val.int (-9223372036854763653)] }]

def dom_idempotent_v8_base_internal_RangeCheck___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854754471), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00e0\u00fd", Val.list [Val.int (2698)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00f9e", Val.int (-5815782740631448771)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (5884099853687727139)], Val.int (-14522)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775651), Val.str "]#_\u0010"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u0002\u0007", Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854729933), Val.int (400)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23), Val.int (-9223372036854763653)] }]

def dom_commutes_v8_base_internal_RangeCheck___init_1 : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854754471), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00e0\u00fd", Val.list [Val.int (2698)]] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u00f9e", Val.int (-5815782740631448771)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (5884099853687727139)], Val.int (-14522)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775651), Val.str "]#_\u0010"] },
   { heap := h0 ++ [], self := none, args := [Val.str "\u0002\u0007", Val.bool true] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854729933), Val.int (400)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23), Val.int (-9223372036854763653)] }]

def dom_runs_v8_base_MulWithWraparound_int16_t_int16_t_int16_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854759946), Val.int (-30192)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-25637), Val.int (-9223372036854775029)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (2698)] },
   { heap := h0 ++ [], self := none, args := [Val.int (13179), Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775726), Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23474), Val.int (-9223372036854730841)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883), Val.int (-32677)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771), Val.int (2)] }]

def dom_returns_v8_base_MulWithWraparound_int16_t_int16_t_int16_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854759946), Val.int (-30192)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-25637), Val.int (-9223372036854775029)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (2698)] },
   { heap := h0 ++ [], self := none, args := [Val.int (13179), Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775726), Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23474), Val.int (-9223372036854730841)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883), Val.int (-32677)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771), Val.int (2)] }]

def dom_commutes_v8_base_MulWithWraparound_int16_t_int16_t_int16_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854759946), Val.int (-30192)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-25637), Val.int (-9223372036854775029)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (2698)] },
   { heap := h0 ++ [], self := none, args := [Val.int (13179), Val.int (74)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775726), Val.int (-9223372036854775672)] },
   { heap := h0 ++ [], self := none, args := [Val.int (23474), Val.int (-9223372036854730841)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883), Val.int (-32677)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771), Val.int (2)] }]

def dom_identity_alStackAddressForSlot_v8_base_Stack_StackSlot_v8_base_Stack_StackSlot : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-14522)] },
   { heap := h0 ++ [], self := none, args := [Val.str "-\u0091\u00f6u\u27c2y\u00ae\u0002"] },
   { heap := h0 ++ [], self := none, args := [Val.int (65536)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854770397)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (94)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181)] }]

def dom_idempotent_alStackAddressForSlot_v8_base_Stack_StackSlot_v8_base_Stack_StackSlot : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-14522)] },
   { heap := h0 ++ [], self := none, args := [Val.str "-\u0091\u00f6u\u27c2y\u00ae\u0002"] },
   { heap := h0 ++ [], self := none, args := [Val.int (65536)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854770397)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (94)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181)] }]

def dom_involutive_alStackAddressForSlot_v8_base_Stack_StackSlot_v8_base_Stack_StackSlot : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-14522)] },
   { heap := h0 ++ [], self := none, args := [Val.str "-\u0091\u00f6u\u27c2y\u00ae\u0002"] },
   { heap := h0 ++ [], self := none, args := [Val.int (65536)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854770397)] },
   { heap := h0 ++ [], self := none, args := [Val.list [Val.int (94)]] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181)] }]

def dom_charact_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-21249), Val.int (-9223372036854775511)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-21249)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (6125780340178803969)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-28819)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-8035)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-109)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775797), Val.int (4191)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-3165)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-19472)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (-2)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854765614), Val.int (-300)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-14)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (-9223372036854773702)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 27461) }]

def dom_charact_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (74), Val.int (-9223372036854749573)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 74) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (6125780340178803969), Val.int (42)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 21) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (-1842855630749095363)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 7144) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-31333)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-109)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (28367)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-8075)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-4370), Val.int (4191)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-179)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (8155596544368608066), Val.int (-9223372036854748347)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-830569662)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (2097065261283699244)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1575225627)) }]

def dom_charact_v8_base_SetPrintStackTrace_void_void : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.str "_\u0095\u001c;\u00b8"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-27237)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775808)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "}Mj\u192f\u1d19\u1c74\u21f5\u00af"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u00b2\u00be\u0086\u00b1\u29cba\u00f6"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1886002477)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u00df\u0088\u1119["] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_SetFatalFunction_void_void : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.str "A\u12e1[~\u00a7\u0002H("] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854730841)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-7)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854775797)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u1ab0k1\u00e4Z\u1d37\u00fdI"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (127)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool false] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_PosixInitializeCommon_void_char : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.bool true] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-7)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-30192)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036559664159)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "l?\u00ad\u00a2"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2698)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (3021723606400056615)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-20836)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_OS_Initialize_duplicate_0_void_char : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.bool false] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u2a8d"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-30093607959703112948291903580161756742)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u2ac6\u0000\u00d2\u00f1%\u00f2\u001b\u05f9"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854746682)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-8035)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_AddressRegion___init : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-5815782740631448771)], Val.str "\nAz\u008a\u2df3"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool false, Val.int (-9052)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u00bf\u00b9\u00e6", Val.int (-9223372036854740054)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "cases", Val.int (74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u0f1b\u0013\u2d9e\u00c7\u09a9\u0c56[\u282c", Val.int (130)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2097065261283699244), Val.int (42)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854731939)], Val.int (-26161)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (8012993533289937693)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_UnsignedDiv32_uint32_t_uint32_t_uint32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-31152), Val.int (-3032)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 10) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-30501), Val.int (-23786)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-8035), Val.int (11)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-730)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (8012993533289937693)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (82), Val.int (-1738374194401833935)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (26614)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1936562) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9052), Val.int (-9223372036854748347)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181), Val.int (8155596544368608066)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1)) }]

def dom_charact_v8_UnsignedDiv64_uint64_t_uint64_t_uint64_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-7), Val.int (130)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833), Val.int (-20706)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 470857515) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854729933), Val.int (1)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 45875) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (22762), Val.int (8320)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 2) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854718492), Val.int (22286)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-903473329)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (11), Val.int (25087)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-8951265655611708266), Val.int (7144)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1611281781)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (65536), Val.int (-8035)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-8)) }]

def dom_charact_v8_UnsignedMod32_uint32_t_uint32_t_uint32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-21249)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (50)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-37)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769302), Val.int (5626624876551845293)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1690317033)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2147483647), Val.int (3021723606400056615)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 2147483647) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-114), Val.int (-9223372036854759946)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-114)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139), Val.int (-8951265655611708266)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1107043363) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-21555), Val.int (-25637)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-21555)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2147483647), Val.int (-9223372033174926866)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 2147483647) }]

def dom_charact_v8_UnsignedMod64_uint64_t_uint64_t_uint64_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (7696070463740520648), Val.int (22286)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 19608) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748136), Val.int (-9223372036854748540)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 27672) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086), Val.int (-8951265655611708266)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 484716564) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-8683), Val.int (13179)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-8683)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (5626624876551845293)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-32479)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (31710)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-2899)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854713668), Val.int (-9223372036854719199)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 62140) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (300000)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-124390)) }]

def dom_charact_v8_WraparoundAdd32_int32_t_int32_t_int32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-20706), Val.int (-30093607959703112948291903580161756742)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1350230232) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854775672)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 24632) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854769961), Val.int (-21249)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-15402)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-32479), Val.int (-9223372033281947594)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-722171561)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-2), Val.int (42)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 40) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-644277784176366389), Val.int (-2147483648)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1367207115) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (7696070463740520648)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1381940048)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312), Val.int (-9223372036854738979)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 61325) }]

def dom_charact_v8_base_Hasher___init : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (400)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2843)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool false] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775807)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "6\u00f4\u2e48"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9324)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-2)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_hash64_uint64_t_uint64_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724594)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-917204782)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (5626624876551845293)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 102271009) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-112999556)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1525946974) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767578)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1516678075)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9324)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 829363293) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775645)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1797990367)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-27237)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-796914655)) }]

def dom_charact_v8_base_hash32_uint32_t_uint32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-895235421)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1266812162) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (12)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-502655605)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-124)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 641467855) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-19472)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 67039986) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (3130535145585281007)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1732517524) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 548403411) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-7)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1567636950) }]

def dom_charact_v8_base_hash_value_size_t_unsigned_char : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033281947594)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372040427604022) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9324)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 18446744073709542292) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (8118)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 8118) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854751312)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854800304) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-7)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 18446744073709551609) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854746682)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854804934) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854721555)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854830061) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036384244755)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372037325306861) }]

def dom_charact_v8_base_hash_value_size_t_shortunsigned : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-300)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 18446744073709551316) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775672)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854775944) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (0)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854773788)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854777828) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854749573)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854802043) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9223372036854827226) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (23563)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 23563) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (4294967296)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 4294967296) }]

def dom_charact_v8_base_internal_MakeStrictNum_StrictNumeric_T : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.bool false] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.bool false) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (1)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.list [Autoform.Core.Val.int 1]) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767797)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-9223372036854767797)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-27237)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-27237)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (8580004217855970090)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 8580004217855970090) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool true] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.bool true) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-26161)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-26161)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (5884099853687727139)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 5884099853687727139) }]

def dom_charact_v8_base_internal_RangeCheck___init : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-95), Val.str "\u00bc\u00e8"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool true, Val.int (-20706)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-25564), Val.int (-22947)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.bool true] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.int (74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775701), Val.int (31710)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775029), Val.list [Val.int (12)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-74), Val.bool true] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_MulWithWraparound_int16_t_int16_t_int16_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854759946), Val.int (-30192)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 31584) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-25637), Val.int (-9223372036854775029)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 17257) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724390), Val.int (2698)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-13948)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (13179), Val.int (74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-7794)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775726), Val.int (-9223372036854775672)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 11152) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (23474), Val.int (-9223372036854730841)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 32542) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883), Val.int (-32677)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-10297)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5815782740631448771), Val.int (2)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 9850) }]

def dom_charact_alStackAddressForSlot_v8_base_Stack_StackSlot_v8_base_Stack_StackSlot : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854732833)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-9223372036854732833)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-14522)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-14522)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "-\u0091\u00f6u\u27c2y\u00ae\u0002"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.str "-öu⟂y®\x02") },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (65536)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 65536) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854770397)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-9223372036854770397)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (94)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.list [Autoform.Core.Val.int 94]) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-9223372033800805883)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854720181)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-9223372036854720181)) }]

end Autoform.SpecsGen.V8Base.Base
