import Autoform.SpecsGen.Basis
import Autoform.Harness.Audit
import Autoform.Generated.LinuxLcm

/-! Generated by `scripts/synth_specs.py`. Do not edit by hand. -/
namespace Autoform.SpecsGen.LinuxLcm

open Autoform.Core Autoform.Refine Autoform.SpecsGen

-- The proofs below are by computation on concrete inputs: the kernel walks the
-- interpreter, and deeply nested calls need more than the default budgets.
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000
set_option cbv.warning false
set_option exponentiation.threshold 4096

abbrev P : Program := Autoform.Generated.LinuxLcm.program

/-- The module-initialiser heap, evaluated once by `initGlobals P 5000 moduleInits` and
frozen into this literal so that the kernel does not re-run the initialisers for every
case of every proof. -/
def h0 : Heap := [{ cls := "<globals>", fields := [], captured := [], payload := Autoform.Core.Payload.none, version := 0 }]

/-- Address of the globals frame. -/
def gref : Ref := 0
def base : Nat := h0.length
def C : Ctx := { dialect := P.dialect, table := P.table, globals := gref,
                 builtinBases := P.builtinBases, properties := P.properties,
                 excClasses := P.excClasses, classDecls := P.classDecls }
def FUEL : Nat := 5000
open Autoform.Generated.LinuxLcm



/-!
# Synthesized specifications — `LinuxLcm`

**Generated by `scripts/synth_specs.py`. Do not edit by hand.**

Every statement below is about `Autoform/Generated/LinuxLcm.lean` *by import*, so a
mutation of the generated module is a mutation of the subject of these theorems
(`scripts/mutate.py --spec-file`). The `#audit_depends` block at the end fails the build
for any theorem that does not mention the implementation it claims to constrain.

What each family claims, in the order of `STRATEGY.md` §4:

* `conform_*` (§4.4, cross-implementation) — the interpreter reproduces, case by case,
  the outcome the **source runtime** produced for the recorded calls to this
  function. The right-hand sides were recorded by `scripts/differential.py`;
  they are not this system's own output, which is what keeps the family from being an
  elaborate `rfl`.
* `runs_*` / `returns_*` (§4.2, structural) — on this domain the interpreter neither
  reaches an untranslated construct nor exhausts its fuel. `EResult` distinguishes
  `.hole` and `.outOfFuel` from behaviour, so this is a real property, and it is stated
  only for functions whose AST *could* violate it.
* `heappure_*`, `const_*`, `projects_*`, `identity_*`, `idempotent_*`, `involutive_*`,
  `commutes_*`, `nonneg_*` (§4.3, algebraic) — laws mined from observed executions and
  **refuted against a fuzzed domain before emission**. Survivors only.
* `uconst_*`, `uproj_*` — universally quantified refinements, proved for every input and
  every fuel budget above a stated bound.

Domains are finite and explicit, and the theorems about them are proved by computation.
That is deliberate: a kernel-checked test is a test whose axiom basis is auditable and
whose subject a mutation gate can attack.

**Fuel.** A law checked at one budget is a weaker claim than it looks, so each law here is
stated as `∀ fuel, FUEL ≤ fuel → …` wherever that could be *proved*: checked at `FUEL` by
computation and transported by `Autoform/FuelMono.lean`'s `applyFunc_fuel_mono`. That
transport needs two side conditions, both discharged rather than assumed — the context is
covered by the unrestricted fuel theorem (including finalizers) and the run did not
end in `outOfFuel` (the `g…` guard, evaluated over the same domain as the law). Where
either fails, the theorem stays at `FUEL` and its generalization is recorded in
`obligations` below as a `Prop`-valued `def` — a statement, not an admission.

There is no `sorry` in this file.

Counts for this run are in `Autoform/SpecsGen/report.json`.
-/

def dom_conform_gcd : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (11), Val.int (7)] }, expected := EResult.val (Val.int (1)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 16 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_gcd : ∀ fuel, FUEL ≤ fuel → ((dom_conform_gcd).all (lawConform C fuel f_gcd)) = true := by
  intro fuel hf
  have hk : 16 ≤ fuel := Nat.le_trans (by decide : 16 ≤ FUEL) hf
  have hchecked : (dom_conform_gcd).all (lawConform C 16 f_gcd) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 16 f_gcd) (lawConform C 16 f_gcd) (lawConform C fuel f_gcd)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_lcm : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2147483648), Val.int (3)] }, expected := EResult.val (Val.int (6442450944)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 32 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_lcm : ∀ fuel, FUEL ≤ fuel → ((dom_conform_lcm).all (lawConform C fuel f_lcm)) = true := by
  intro fuel hf
  have hk : 32 ≤ fuel := Nat.le_trans (by decide : 32 ≤ FUEL) hf
  have hchecked : (dom_conform_lcm).all (lawConform C 32 f_lcm) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 32 f_lcm) (lawConform C 32 f_lcm) (lawConform C fuel f_lcm)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

/-- Everything this module states but does not prove. A `Prop`-valued `def` asserts nothing, so nothing here is admitted. -/
def obligations : List OpenObligation :=
  []

#eval IO.println (renderObligations "LinuxLcm" obligations)

/-! ## Anti-vacuity gate

`#audit_depends` fails the build if a theorem's proof term never mentions the generated definition it claims to be about — the necessary half of the gate. The sufficient half is `scripts/mutate.py`, run against this file. -/

#audit_depends conform_gcd on f_gcd
#audit_depends conform_lcm on f_lcm

/-! ## Axiom basis

`#audit_axioms` fails the build on `sorryAx`, `ofReduceBool` or `ofReduceNat`, so "no admitted step, no `native_decide`" is checked here rather than asserted in prose. -/

#audit_axioms conform_gcd
#audit_axioms conform_lcm

end Autoform.SpecsGen.LinuxLcm
