import Autoform.SpecsGen.Basis
import Autoform.Harness.Audit
import Autoform.Generated.V8BaseSample

/-! Generated by `scripts/synth_specs.py`. Do not edit by hand. -/
namespace Autoform.SpecsGen.V8BaseSample

open Autoform.Core Autoform.Refine Autoform.SpecsGen

-- The proofs below are by computation on concrete inputs: the kernel walks the
-- interpreter, and deeply nested calls need more than the default budgets.
set_option maxRecDepth 20000
set_option maxHeartbeats 1000000

abbrev P : Program := Autoform.Generated.V8BaseSample.program

/-- The module-initialiser heap, evaluated once by `initGlobals P 5000 moduleInits` and
frozen into this literal so that the kernel does not re-run the initialisers for every
case of every proof. -/
def h0 : Heap := [{ cls := "<globals>", fields := [], captured := [] }]

/-- Address of the globals frame. -/
def gref : Ref := 0
def base : Nat := h0.length
def C : Ctx := { dialect := P.dialect, table := P.table, globals := gref }
def FUEL : Nat := 400
open Autoform.Generated.V8BaseSample

/-- Every function body reachable in this program is `tryFinally`-free, so
`Autoform/FuelMono.lean`'s monotonicity theorems apply to this context. Checked by
computation over the whole function table, not assumed. `Stmt.tryFinally` is the single
construct that breaks fuel monotonicity (`FuelMono.tryFinally_breaks_fuel_mono` exhibits a
program answering 1 at fuel 4 and 2 at fuel 5), so this is the hypothesis that decides
whether a law checked at one budget holds at every larger one. -/
theorem C_tfFree : TFFreeCtx C := by
  refine tfFree_of_table ?_
  have h : (C.table.all fun p => tfFreeS p.2.body) = true := by rfl
  exact fun p hp => (List.all_eq_true.mp h) p hp


/-!
# Synthesized specifications — `V8Base`

**Generated by `scripts/synth_specs.py`. Do not edit by hand.**

Every statement below is about `Autoform/Generated/V8Base.lean` *by import*, so a
mutation of the generated module is a mutation of the subject of these theorems
(`scripts/mutate.py --spec-file`). The `#audit_depends` block at the end fails the build
for any theorem that does not mention the implementation it claims to constrain.

What each family claims, in the order of `STRATEGY.md` §4:

* `conform_*` (§4.4, cross-implementation) — the interpreter reproduces, case by case,
  the outcome **CPython** produced when the repository's own test suite called this
  function. The right-hand sides were recorded by `scripts/differential.py`'s trace hook;
  they are not this system's own output, which is what keeps the family from being an
  elaborate `rfl`.
* `runs_*` / `returns_*` (§4.2, structural) — on this domain the interpreter neither
  reaches an untranslated construct nor exhausts its fuel. `EResult` distinguishes
  `.hole` and `.outOfFuel` from behaviour, so this is a real property, and it is stated
  only for functions whose AST *could* violate it.
* `heappure_*`, `const_*`, `projects_*`, `identity_*`, `idempotent_*`, `involutive_*`,
  `commutes_*`, `nonneg_*` (§4.3, algebraic) — laws mined from observed executions and
  **refuted against a fuzzed domain before emission**. Survivors only.
* `uconst_*`, `uproj_*` — universally quantified refinements, proved for every input and
  every fuel budget above a stated bound.

Domains are finite and explicit, and the theorems about them are proved by computation.
That is deliberate: a kernel-checked test is a test whose axiom basis is auditable and
whose subject a mutation gate can attack.

**Fuel.** A law checked at one budget is a weaker claim than it looks, so each law here is
stated as `∀ fuel, FUEL ≤ fuel → …` wherever that could be *proved*: checked at `FUEL` by
computation and transported by `Autoform/FuelMono.lean`'s `applyFunc_fuel_mono`. That
transport needs two side conditions, both discharged rather than assumed — the context is
`tryFinally`-free (`C_tfFree`, by computation over the function table) and the run did not
end in `outOfFuel` (the `g…` guard, evaluated over the same domain as the law). Where
either fails, the theorem stays at `FUEL` and its generalization is recorded in
`obligations` below as a `Prop`-valued `def` — a statement, not an admission.

There is no `sorry` in this file.

Counts for this run are in `Autoform/SpecsGen/report.json`.
-/

def dom_runs_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-21249), Val.int (-9223372036854775511)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (6125780340178803969)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-8035)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775797), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (-2)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854765614), Val.int (-300)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (-9223372036854773702)] }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at `FUEL` by computation, then transported by `FuelMono.applyFunc_fuel_mono`.
The `gRun` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem runs_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : ∀ fuel, FUEL ≤ fuel → ((dom_runs_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t).all (lawRuns C fuel f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_)) = true := by
  intro fuel hf
  exact all_transfer _ (gRun C FUEL f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_) (lawRuns C FUEL f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_) (lawRuns C fuel f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_)
    (fun c hgc hlc =>
      lawRuns_fuel_mono (hctx := C_tfFree) (hfn := (by rfl : tfFreeS f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_.body = true))
        (hk := hf) (hg := hgc) (h := hlc))
    (by rfl) (by rfl)

def dom_returns_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (-21249), Val.int (-9223372036854775511)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (6125780340178803969)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-8035)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775797), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-19472)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (-2)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854765614), Val.int (-300)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (-9223372036854773702)] }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at `FUEL` by computation, then transported by `FuelMono.applyFunc_fuel_mono`.
The `gRun` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem returns_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : ∀ fuel, FUEL ≤ fuel → ((dom_returns_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t).all (lawReturns C fuel f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_)) = true := by
  intro fuel hf
  exact all_transfer _ (gRun C FUEL f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_) (lawReturns C FUEL f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_) (lawReturns C fuel f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_)
    (fun c hgc hlc =>
      lawReturns_fuel_mono (hctx := C_tfFree) (hfn := (by rfl : tfFreeS f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_.body = true))
        (hk := hf) (hg := hgc) (h := hlc))
    (by rfl) (by rfl)

def dom_runs_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (74), Val.int (-9223372036854749573)] },
   { heap := h0 ++ [], self := none, args := [Val.int (6125780340178803969), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (-1842855630749095363)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-31333)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (28367)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-4370), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8155596544368608066), Val.int (-9223372036854748347)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (2097065261283699244)] }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at `FUEL` by computation, then transported by `FuelMono.applyFunc_fuel_mono`.
The `gRun` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem runs_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : ∀ fuel, FUEL ≤ fuel → ((dom_runs_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t).all (lawRuns C fuel f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_)) = true := by
  intro fuel hf
  exact all_transfer _ (gRun C FUEL f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_) (lawRuns C FUEL f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_) (lawRuns C fuel f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_)
    (fun c hgc hlc =>
      lawRuns_fuel_mono (hctx := C_tfFree) (hfn := (by rfl : tfFreeS f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_.body = true))
        (hk := hf) (hg := hgc) (h := hlc))
    (by rfl) (by rfl)

def dom_returns_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : List Case :=
  [{ heap := h0 ++ [], self := none, args := [Val.int (74), Val.int (-9223372036854749573)] },
   { heap := h0 ++ [], self := none, args := [Val.int (6125780340178803969), Val.int (42)] },
   { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (-1842855630749095363)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-31333)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (28367)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-4370), Val.int (4191)] },
   { heap := h0 ++ [], self := none, args := [Val.int (8155596544368608066), Val.int (-9223372036854748347)] },
   { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (2097065261283699244)] }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at `FUEL` by computation, then transported by `FuelMono.applyFunc_fuel_mono`.
The `gRun` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem returns_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : ∀ fuel, FUEL ≤ fuel → ((dom_returns_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t).all (lawReturns C fuel f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_)) = true := by
  intro fuel hf
  exact all_transfer _ (gRun C FUEL f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_) (lawReturns C FUEL f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_) (lawReturns C fuel f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_)
    (fun c hgc hlc =>
      lawReturns_fuel_mono (hctx := C_tfFree) (hfn := (by rfl : tfFreeS f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_.body = true))
        (hk := hf) (hg := hgc) (h := hlc))
    (by rfl) (by rfl)

theorem uconst_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool :
    Refines P "v8.base.debug.EnableInProcessStackDumping<duplicate>0:bool()" 8
      (fun args => posRejected f_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool__ args = false)
      (fun _ => .ret (Val.bool false)) := by
  intro args hdom
  simp [posRejected, f_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool__, Func.posParams] at hdom
  refine forall_ge_of_forall_add (N := 8) ?_
  intro k
  rw [runFunc_of_resolve _ _ _ _ f_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool__ rfl]
  first
    | simp [applyFunc, execStmt, evalExpr, Env.set, f_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool__, ctxOf, P, hdom, Nat.not_lt.mpr hdom]
    | simp [applyFunc, execStmt, evalExpr, Env.set, f_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool__, ctxOf, P, hdom]

theorem uconst_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const :
    Refines P "v8.base.debug.BacktraceOutputHandler.OutputFileDescriptor:int()<const>" 8
      (fun args => posRejected f_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const_ args = false)
      (fun _ => .ret (Val.int (0))) := by
  intro args hdom
  simp [posRejected, f_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const_, Func.posParams] at hdom
  refine forall_ge_of_forall_add (N := 8) ?_
  intro k
  rw [runFunc_of_resolve _ _ _ _ f_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const_ rfl]
  first
    | simp [applyFunc, execStmt, evalExpr, Env.set, f_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const_, ctxOf, P, hdom, Nat.not_lt.mpr hdom]
    | simp [applyFunc, execStmt, evalExpr, Env.set, f_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const_, ctxOf, P, hdom]

def dom_charact_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-21249), Val.int (-9223372036854775511)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-21249)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (6125780340178803969)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-28819)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-8035)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-109)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775797), Val.int (4191)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-3165)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (-19472)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 0) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033277473987), Val.int (-2)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854765614), Val.int (-300)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-14)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854748347), Val.int (-9223372036854773702)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 27461) }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at `FUEL` by computation, then transported by `FuelMono.applyFunc_fuel_mono`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem charact_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t : ∀ fuel, FUEL ≤ fuel → ((dom_charact_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t).all (lawConform C fuel f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_)) = true := by
  intro fuel hf
  exact all_transfer _ (gRunObs C FUEL f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_) (lawConform C FUEL f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_) (lawConform C fuel f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_)
    (fun c hgc hlc =>
      lawConform_fuel_mono (hctx := C_tfFree) (hfn := (by rfl : tfFreeS f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_.body = true))
        (hk := hf) (hg := hgc) (h := hlc))
    (by rfl) (by rfl)

def dom_charact_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (74), Val.int (-9223372036854749573)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 74) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (6125780340178803969), Val.int (42)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 21) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (7144), Val.int (-1842855630749095363)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 7144) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-109), Val.int (-31333)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-109)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5196161572062811644), Val.int (28367)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-8075)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-4370), Val.int (4191)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-179)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (8155596544368608066), Val.int (-9223372036854748347)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-830569662)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-5262057860072004979), Val.int (2097065261283699244)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1575225627)) }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at `FUEL` by computation, then transported by `FuelMono.applyFunc_fuel_mono`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem charact_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t : ∀ fuel, FUEL ≤ fuel → ((dom_charact_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t).all (lawConform C fuel f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_)) = true := by
  intro fuel hf
  exact all_transfer _ (gRunObs C FUEL f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_) (lawConform C FUEL f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_) (lawConform C fuel f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_)
    (fun c hgc hlc =>
      lawConform_fuel_mono (hctx := C_tfFree) (hfn := (by rfl : tfFreeS f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_.body = true))
        (hk := hf) (hg := hgc) (h := hlc))
    (by rfl) (by rfl)

/-- Everything this module states but does not prove. A `Prop`-valued `def` asserts nothing, so nothing here is admitted. -/
def obligations : List OpenObligation :=
  []

#eval IO.println (renderObligations "V8BaseSample" obligations)

/-! ## Anti-vacuity gate

`#audit_depends` fails the build if a theorem's proof term never mentions the generated definition it claims to be about — the necessary half of the gate. The sufficient half is `scripts/mutate.py`, run against this file. -/

#audit_depends runs_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t on f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_
#audit_depends returns_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t on f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_
#audit_depends runs_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t on f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_
#audit_depends returns_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t on f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_
#audit_depends uconst_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool on f_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool__
#audit_depends uconst_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const on f_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const_
#audit_depends charact_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t on f_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t_
#audit_depends charact_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t on f_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t_

/-! ## Axiom basis

`#audit_axioms` fails the build on `sorryAx`, `ofReduceBool` or `ofReduceNat`, so "no admitted step, no `native_decide`" is checked here rather than asserted in prose. -/

#audit_axioms runs_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t
#audit_axioms returns_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t
#audit_axioms runs_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t
#audit_axioms returns_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t
#audit_axioms uconst_v8_base_debug_EnableInProcessStackDumping_duplicate_0_bool
#audit_axioms uconst_v8_base_debug_BacktraceOutputHandler_OutputFileDescriptor_int___const
#audit_axioms charact_v8_base_bits_SignedMod32_int32_t_int32_t_int32_t
#audit_axioms charact_v8_base_bits_SignedMod64_int64_t_int64_t_int64_t

end Autoform.SpecsGen.V8BaseSample
