import Autoform.SpecsGen.Basis
import Autoform.Harness.Audit
import Autoform.Generated.V8Base

/-! Generated by `scripts/synth_specs.py`. Do not edit by hand. -/
namespace Autoform.SpecsGen.V8Base

open Autoform.Core Autoform.Refine Autoform.SpecsGen

-- The proofs below are by computation on concrete inputs: the kernel walks the
-- interpreter, and deeply nested calls need more than the default budgets.
set_option maxRecDepth 20000
set_option maxHeartbeats 1000000

abbrev P : Program := Autoform.Generated.V8Base.program

/-- The module-initialiser heap, evaluated once by `initGlobals P 5000 moduleInits` and
frozen into this literal so that the kernel does not re-run the initialisers for every
case of every proof. -/
def h0 : Heap := [{ cls := "<globals>", fields := [], captured := [] }]

/-- Address of the globals frame. -/
def gref : Ref := 0
def base : Nat := h0.length
def C : Ctx := { dialect := P.dialect, table := P.table, globals := gref }
def FUEL : Nat := 400
open Autoform.Generated.V8Base

/-- Every function body reachable in this program is `tryFinally`-free, so
`Autoform/FuelMono.lean`'s monotonicity theorems apply to this context. Checked by
computation over the whole function table, not assumed. `Stmt.tryFinally` is the single
construct that breaks fuel monotonicity (`FuelMono.tryFinally_breaks_fuel_mono` exhibits a
program answering 1 at fuel 4 and 2 at fuel 5), so this is the hypothesis that decides
whether a law checked at one budget holds at every larger one. -/
theorem C_tfFree : TFFreeCtx C := by
  refine tfFree_of_table ?_
  have h : (C.table.all fun p => tfFreeS p.2.body) = true := by rfl
  exact fun p hp => (List.all_eq_true.mp h) p hp


/-!
# Synthesized specifications — `V8Base`

**Generated by `scripts/synth_specs.py`. Do not edit by hand.**

Every statement below is about `Autoform/Generated/V8Base.lean` *by import*, so a
mutation of the generated module is a mutation of the subject of these theorems
(`scripts/mutate.py --spec-file`). The `#audit_depends` block at the end fails the build
for any theorem that does not mention the implementation it claims to constrain.

What each family claims, in the order of `STRATEGY.md` §4:

* `conform_*` (§4.4, cross-implementation) — the interpreter reproduces, case by case,
  the outcome **CPython** produced when the repository's own test suite called this
  function. The right-hand sides were recorded by `scripts/differential.py`'s trace hook;
  they are not this system's own output, which is what keeps the family from being an
  elaborate `rfl`.
* `runs_*` / `returns_*` (§4.2, structural) — on this domain the interpreter neither
  reaches an untranslated construct nor exhausts its fuel. `EResult` distinguishes
  `.hole` and `.outOfFuel` from behaviour, so this is a real property, and it is stated
  only for functions whose AST *could* violate it.
* `heappure_*`, `const_*`, `projects_*`, `identity_*`, `idempotent_*`, `involutive_*`,
  `commutes_*`, `nonneg_*` (§4.3, algebraic) — laws mined from observed executions and
  **refuted against a fuzzed domain before emission**. Survivors only.
* `uconst_*`, `uproj_*` — universally quantified refinements, proved for every input and
  every fuel budget above a stated bound.

Domains are finite and explicit, and the theorems about them are proved by computation.
That is deliberate: a kernel-checked test is a test whose axiom basis is auditable and
whose subject a mutation gate can attack.

**Fuel.** A law checked at one budget is a weaker claim than it looks, so each law here is
stated as `∀ fuel, FUEL ≤ fuel → …` wherever that could be *proved*: checked at `FUEL` by
computation and transported by `Autoform/FuelMono.lean`'s `applyFunc_fuel_mono`. That
transport needs two side conditions, both discharged rather than assumed — the context is
`tryFinally`-free (`C_tfFree`, by computation over the function table) and the run did not
end in `outOfFuel` (the `g…` guard, evaluated over the same domain as the law). Where
either fails, the theorem stays at `FUEL` and its generalization is recorded in
`obligations` below as a `Prop`-valued `def` — a statement, not an admission.

There is no `sorry` in this file.

Counts for this run are in `Autoform/SpecsGen/report.json`.
-/


def dom_charact_v8_base_AddressRegion___init : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-5815782740631448771)], Val.str "\nAz\u008a\u2df3"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool false, Val.int (-9052)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u00bf\u00b9\u00e6", Val.int (-9223372036854740054)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "cases", Val.int (74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u0f1b\u0013\u2d9e\u00c7\u09a9\u0c56[\u282c", Val.int (130)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2097065261283699244), Val.int (42)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.list [Val.int (-9223372036854731939)], Val.int (-26161)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-28819), Val.int (8012993533289937693)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_Hasher___init : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (400)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2843)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool false] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "\u009e\u0096\u00e9-\t\u00d1\u00cf["] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775807)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.str "6\u00f4\u2e48"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9324)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-2)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

def dom_charact_v8_base_hash64_uint64_t_uint64_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854724594)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-917204782)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (5626624876551845293)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 102271009) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372033800805883)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-112999556)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854752086)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1525946974) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854767578)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1516678075)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9324)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 829363293) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775645)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-1797990367)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-27237)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-796914655)) }]

def dom_charact_v8_base_hash32_uint32_t_uint32_t : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-895235421)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1266812162) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (12)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int (-502655605)) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-124)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 641467855) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-19472)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 67039986) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (3130535145585281007)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1732517524) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775616)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 548403411) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-7)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.int 1567636950) }]

def dom_charact_v8_base_internal_RangeCheck___init : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (-95), Val.str "\u00bc\u00e8"] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.bool true, Val.int (-20706)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-25564), Val.int (-22947)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.bool true] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-23786), Val.int (74)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775701), Val.int (31710)] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775029), Val.list [Val.int (12)]] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-74), Val.bool true] }, expected := Autoform.Core.EResult.val (Autoform.Core.Val.unit) }]

#eval IO.println (repr ((dom_charact_v8_base_AddressRegion___init).map (fun o => ((runCase C FUEL f_v8_base_AddressRegion___init__ o.case).2, o.expected))))
#eval IO.println (repr ((dom_charact_v8_base_Hasher___init).map (fun o => ((runCase C FUEL f_v8_base_Hasher___init__ o.case).2, o.expected))))
#eval IO.println (repr ((dom_charact_v8_base_hash64_uint64_t_uint64_t).map (fun o => ((runCase C FUEL f_v8_base_hash64_uint64_t_uint64_t_ o.case).2, o.expected))))
#eval IO.println (repr ((dom_charact_v8_base_hash32_uint32_t_uint32_t).map (fun o => ((runCase C FUEL f_v8_base_hash32_uint32_t_uint32_t_ o.case).2, o.expected))))
#eval IO.println (repr ((dom_charact_v8_base_internal_RangeCheck___init).map (fun o => ((runCase C FUEL f_v8_base_internal_RangeCheck___init__ o.case).2, o.expected))))
