import Autoform.SpecsGen.Basis
import Autoform.Harness.Audit
import Autoform.Generated.PipelineGo

/-! Generated by `scripts/synth_specs.py`. Do not edit by hand. -/
namespace Autoform.SpecsGen.PipelineGo

open Autoform.Core Autoform.Refine Autoform.SpecsGen

-- The proofs below are by computation on concrete inputs: the kernel walks the
-- interpreter, and deeply nested calls need more than the default budgets.
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000
set_option cbv.warning false
set_option exponentiation.threshold 4096

abbrev P : Program := Autoform.Generated.PipelineGo.program

/-- The module-initialiser heap, evaluated once by `initGlobals P 5000 moduleInits` and
frozen into this literal so that the kernel does not re-run the initialisers for every
case of every proof. -/
def h0 : Heap := [{ cls := "<globals>", fields := [], captured := [], payload := Autoform.Core.Payload.none, version := 0 }]

/-- Address of the globals frame. -/
def gref : Ref := 0
def base : Nat := h0.length
def C : Ctx := { dialect := P.dialect, table := P.table, globals := gref,
                 builtinBases := P.builtinBases, properties := P.properties,
                 excClasses := P.excClasses, classDecls := P.classDecls }
def FUEL : Nat := 5000
open Autoform.Generated.PipelineGo



/-!
# Synthesized specifications — `PipelineGo`

**Generated by `scripts/synth_specs.py`. Do not edit by hand.**

Every statement below is about `Autoform/Generated/PipelineGo.lean` *by import*, so a
mutation of the generated module is a mutation of the subject of these theorems
(`scripts/mutate.py --spec-file`). The `#audit_depends` block at the end fails the build
for any theorem that does not mention the implementation it claims to constrain.

What each family claims, in the order of `STRATEGY.md` §4:

* `conform_*` (§4.4, cross-implementation) — the interpreter reproduces, case by case,
  the outcome the **source runtime** produced for the recorded calls to this
  function. The right-hand sides were recorded by `scripts/differential.py`;
  they are not this system's own output, which is what keeps the family from being an
  elaborate `rfl`.
* `runs_*` / `returns_*` (§4.2, structural) — on this domain the interpreter neither
  reaches an untranslated construct nor exhausts its fuel. `EResult` distinguishes
  `.hole` and `.outOfFuel` from behaviour, so this is a real property, and it is stated
  only for functions whose AST *could* violate it.
* `heappure_*`, `const_*`, `projects_*`, `identity_*`, `idempotent_*`, `involutive_*`,
  `commutes_*`, `nonneg_*` (§4.3, algebraic) — laws mined from observed executions and
  **refuted against a fuzzed domain before emission**. Survivors only.
* `uconst_*`, `uproj_*` — universally quantified refinements, proved for every input and
  every fuel budget above a stated bound.

Domains are finite and explicit, and the theorems about them are proved by computation.
That is deliberate: a kernel-checked test is a test whose axiom basis is auditable and
whose subject a mutation gate can attack.

**Fuel.** A law checked at one budget is a weaker claim than it looks, so each law here is
stated as `∀ fuel, FUEL ≤ fuel → …` wherever that could be *proved*: checked at `FUEL` by
computation and transported by `Autoform/FuelMono.lean`'s `applyFunc_fuel_mono`. That
transport needs two side conditions, both discharged rather than assumed — the context is
covered by the unrestricted fuel theorem (including finalizers) and the run did not
end in `outOfFuel` (the `g…` guard, evaluated over the same domain as the law). Where
either fails, the theorem stays at `FUEL` and its generalization is recorded in
`obligations` below as a `Prop`-valued `def` — a statement, not an admission.

There is no `sorry` in this file.

Counts for this run are in `Autoform/SpecsGen/report.json`.
-/

def dom_conform_numbers_Add : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (1)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1), Val.int (-1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1), Val.int (9223372036854775807)] }, expected := EResult.val (Val.int (9223372036854775806)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.int (-9223372036854775808)] }, expected := EResult.val (Val.int (-1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808), Val.int (2)] }, expected := EResult.val (Val.int (-9223372036854775806)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Add : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Add).all (lawConform C fuel f_numbers_Add)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Add).all (lawConform C 4 f_numbers_Add) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_Add) (lawConform C 4 f_numbers_Add) (lawConform C fuel f_numbers_Add)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Bump : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1)] }, expected := EResult.val (Val.int (2)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (127)] }, expected := EResult.val (Val.int (-128)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-128)] }, expected := EResult.val (Val.int (-127)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Bump : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Bump).all (lawConform C fuel f_numbers_Bump)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Bump).all (lawConform C 8 f_numbers_Bump) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_numbers_Bump) (lawConform C 8 f_numbers_Bump) (lawConform C fuel f_numbers_Bump)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Constant : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [] }, expected := EResult.val (Val.int (9223372036854775808)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Constant : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Constant).all (lawConform C fuel f_numbers_Constant)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Constant).all (lawConform C 4 f_numbers_Constant) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_Constant) (lawConform C 4 f_numbers_Constant) (lawConform C fuel f_numbers_Constant)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_ContextShift : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1)] }, expected := EResult.val (Val.int (2)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2)] }, expected := EResult.val (Val.int (4)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (18446744073709551615)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775808)] }, expected := EResult.val (Val.int (0)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_ContextShift : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_ContextShift).all (lawConform C fuel f_numbers_ContextShift)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_ContextShift).all (lawConform C 4 f_numbers_ContextShift) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_ContextShift) (lawConform C 4 f_numbers_ContextShift) (lawConform C fuel f_numbers_ContextShift)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Div : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1), Val.int (-1)] }, expected := EResult.val (Val.int (-1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1), Val.int (9223372036854775807)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.int (-9223372036854775808)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808), Val.int (2)] }, expected := EResult.val (Val.int (-4611686018427387904)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Div : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Div).all (lawConform C fuel f_numbers_Div)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Div).all (lawConform C 4 f_numbers_Div) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_Div) (lawConform C 4 f_numbers_Div) (lawConform C fuel f_numbers_Div)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Inc : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1)] }, expected := EResult.val (Val.int (2)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807)] }, expected := EResult.val (Val.int (-9223372036854775808)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808)] }, expected := EResult.val (Val.int (-9223372036854775807)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Inc : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Inc).all (lawConform C fuel f_numbers_Inc)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Inc).all (lawConform C 8 f_numbers_Inc) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_numbers_Inc) (lawConform C 8 f_numbers_Inc) (lawConform C fuel f_numbers_Inc)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Right : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1), Val.int (2)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1), Val.int (18446744073709551615)] }, expected := EResult.val (Val.int (-1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.int (9223372036854775808)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808), Val.int (31)] }, expected := EResult.val (Val.int (-4294967296)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Right : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Right).all (lawConform C fuel f_numbers_Right)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Right).all (lawConform C 4 f_numbers_Right) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_Right) (lawConform C 4 f_numbers_Right) (lawConform C fuel f_numbers_Right)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Shift : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1), Val.int (2)] }, expected := EResult.val (Val.int (4)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2), Val.int (18446744073709551615)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (18446744073709551615), Val.int (9223372036854775808)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775808), Val.int (31)] }, expected := EResult.val (Val.int (0)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Shift : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Shift).all (lawConform C fuel f_numbers_Shift)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Shift).all (lawConform C 4 f_numbers_Shift) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_Shift) (lawConform C 4 f_numbers_Shift) (lawConform C fuel f_numbers_Shift)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_numbers_Word : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (1)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (1), Val.int (-1)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-1), Val.int (9223372036854775807)] }, expected := EResult.val (Val.int (9223372036854775806)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9223372036854775807), Val.int (-9223372036854775808)] }, expected := EResult.val (Val.int (-1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-9223372036854775808), Val.int (2)] }, expected := EResult.val (Val.int (-9223372036854775806)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 4 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_numbers_Word : ∀ fuel, FUEL ≤ fuel → ((dom_conform_numbers_Word).all (lawConform C fuel f_numbers_Word)) = true := by
  intro fuel hf
  have hk : 4 ≤ fuel := Nat.le_trans (by decide : 4 ≤ FUEL) hf
  have hchecked : (dom_conform_numbers_Word).all (lawConform C 4 f_numbers_Word) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 4 f_numbers_Word) (lawConform C 4 f_numbers_Word) (lawConform C fuel f_numbers_Word)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

/-- Everything this module states but does not prove. A `Prop`-valued `def` asserts nothing, so nothing here is admitted. -/
def obligations : List OpenObligation :=
  []

#eval IO.println (renderObligations "PipelineGo" obligations)

/-! ## Anti-vacuity gate

`#audit_depends` fails the build if a theorem's proof term never mentions the generated definition it claims to be about — the necessary half of the gate. The sufficient half is `scripts/mutate.py`, run against this file. -/

#audit_depends conform_numbers_Add on f_numbers_Add
#audit_depends conform_numbers_Bump on f_numbers_Bump
#audit_depends conform_numbers_Constant on f_numbers_Constant
#audit_depends conform_numbers_ContextShift on f_numbers_ContextShift
#audit_depends conform_numbers_Div on f_numbers_Div
#audit_depends conform_numbers_Inc on f_numbers_Inc
#audit_depends conform_numbers_Right on f_numbers_Right
#audit_depends conform_numbers_Shift on f_numbers_Shift
#audit_depends conform_numbers_Word on f_numbers_Word

/-! ## Axiom basis

`#audit_axioms` fails the build on `sorryAx`, `ofReduceBool` or `ofReduceNat`, so "no admitted step, no `native_decide`" is checked here rather than asserted in prose. -/

#audit_axioms conform_numbers_Add
#audit_axioms conform_numbers_Bump
#audit_axioms conform_numbers_Constant
#audit_axioms conform_numbers_ContextShift
#audit_axioms conform_numbers_Div
#audit_axioms conform_numbers_Inc
#audit_axioms conform_numbers_Right
#audit_axioms conform_numbers_Shift
#audit_axioms conform_numbers_Word

end Autoform.SpecsGen.PipelineGo
