"""Runtime tracing support for Autoform's test-first workflow.

This module is loaded through a temporary ``sitecustomize.py`` generated by the CLI.
It deliberately stays dependency-free so it can run inside a target project's normal
Python test environment.
"""
from __future__ import annotations

import atexit
import json
import os
import sys
import threading
from pathlib import Path
from types import FrameType
from typing import Any

_INSTALLED = False
_LOCK = threading.Lock()
_COUNTER = 0
_ACTIVE: dict[int, dict[str, Any]] = {}
_OUT = None
_SOURCE_ROOT: Path | None = None
_EXCLUDE_TESTS = True
_MAX_REPR = 240


def _under(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root)
        return True
    except ValueError:
        return False
    except OSError:
        return False


def _is_test_file(path: Path) -> bool:
    parts = {part.lower() for part in path.parts}
    return "tests" in parts or path.name.startswith("test_") or path.name.endswith("_test.py")


def _should_trace(frame: FrameType) -> bool:
    if _SOURCE_ROOT is None:
        return False
    filename = frame.f_code.co_filename
    if not filename or filename.startswith("<"):
        return False
    path = Path(filename)
    if path.suffix != ".py":
        return False
    if not _under(path, _SOURCE_ROOT):
        return False
    if _EXCLUDE_TESTS and _is_test_file(path):
        return False
    return True


def _safe_json(value: Any, depth: int = 0) -> Any:
    if depth > 4:
        return {"type": type(value).__name__, "repr": "..."}
    if value is None or isinstance(value, (bool, int, float, str)):
        return value
    if isinstance(value, (list, tuple)):
        return [_safe_json(item, depth + 1) for item in list(value)[:50]]
    if isinstance(value, dict):
        out: dict[str, Any] = {}
        for idx, (key, item) in enumerate(value.items()):
            if idx >= 50:
                out["..."] = {"type": "truncated", "repr": "more dictionary entries omitted"}
                break
            out[str(_safe_json(key, depth + 1))] = _safe_json(item, depth + 1)
        return out
    try:
        text = repr(value)
    except Exception as exc:  # pragma: no cover - defensive against hostile reprs
        text = f"<repr failed: {type(exc).__name__}>"
    if len(text) > _MAX_REPR:
        text = text[: _MAX_REPR - 3] + "..."
    return {"type": type(value).__name__, "repr": text}


def _function_name(frame: FrameType) -> str:
    module = frame.f_globals.get("__name__") or "<module>"
    qualname = getattr(frame.f_code, "co_qualname", frame.f_code.co_name)
    return f"{module}.{qualname}"


def _args(frame: FrameType) -> tuple[list[Any], dict[str, Any]]:
    code = frame.f_code
    local = frame.f_locals
    positional_count = code.co_argcount
    names = list(code.co_varnames[:positional_count])
    args = [_safe_json(local[name]) for name in names if name in local]
    kwargs: dict[str, Any] = {}
    kw_start = positional_count
    kw_end = kw_start + code.co_kwonlyargcount
    for name in code.co_varnames[kw_start:kw_end]:
        if name in local:
            kwargs[name] = _safe_json(local[name])
    return args, kwargs


def _write(obs: dict[str, Any]) -> None:
    if _OUT is None:
        return
    with _LOCK:
        _OUT.write(json.dumps(obs, ensure_ascii=False, sort_keys=True) + "\n")
        _OUT.flush()


def _trace(frame: FrameType, event: str, arg: Any):
    global _COUNTER
    frame_id = id(frame)
    if event == "call":
        if not _should_trace(frame):
            return None
        with _LOCK:
            _COUNTER += 1
            obs_id = f"obs-{_COUNTER:06d}"
        args, kwargs = _args(frame)
        try:
            rel = str(Path(frame.f_code.co_filename).resolve().relative_to(_SOURCE_ROOT)) if _SOURCE_ROOT else frame.f_code.co_filename
        except Exception:
            rel = frame.f_code.co_filename
        _ACTIVE[frame_id] = {
            "id": obs_id,
            "function": _function_name(frame),
            "source_file": rel,
            "args": args,
            "kwargs": kwargs,
            "coverage": [],
        }
        return _trace
    obs = _ACTIVE.get(frame_id)
    if obs is None:
        return _trace
    if event == "line":
        loc = f"{obs.get('source_file', frame.f_code.co_filename)}:{frame.f_lineno}"
        if not obs["coverage"] or obs["coverage"][-1] != loc:
            obs["coverage"].append(loc)
    elif event == "exception":
        exc_type, exc, _tb = arg
        obs["exception"] = f"{getattr(exc_type, '__name__', str(exc_type))}: {exc}"
    elif event == "return":
        obs = _ACTIVE.pop(frame_id, obs)
        if "exception" not in obs:
            obs["result"] = _safe_json(arg)
        _write(obs)
    return _trace


def install() -> None:
    """Install the trace hook when the required environment variables are present."""
    global _INSTALLED, _OUT, _SOURCE_ROOT, _EXCLUDE_TESTS
    if _INSTALLED:
        return
    output = os.environ.get("AUTOFORM_TRACE_OUTPUT")
    source = os.environ.get("AUTOFORM_TRACE_SOURCE")
    if not output or not source:
        return
    _SOURCE_ROOT = Path(source).expanduser().resolve()
    _EXCLUDE_TESTS = os.environ.get("AUTOFORM_TRACE_INCLUDE_TESTS", "0") not in {"1", "true", "TRUE", "yes", "YES"}
    Path(output).expanduser().parent.mkdir(parents=True, exist_ok=True)
    _OUT = open(Path(output).expanduser(), "w", encoding="utf-8")
    atexit.register(lambda: _OUT and _OUT.close())
    _INSTALLED = True
    sys.settrace(_trace)
    threading.settrace(_trace)
