"""Emit stage: the properties that survived become ordinary tests of the target project.

For each statement whose check status is BOUNDED_HOLDS (and, when a judge ran, each
repaired statement adjudication accepted) this stage writes pytest functions into
`<target>/tests/autoform_generated/test_<module>.py`, where `<target>` is the analysed
source tree (`--emit-dir` overrides the directory):

  concrete tests   one per domain point of the check stage whose real CPython outcome
                   satisfies the statement's `pre` and `post` *as evaluated by Lean on that
                   outcome* (one `#eval` per function, over the same `pre_`/`post_`
                   definitions the check stage certified). The test rebuilds the arguments
                   (receivers from their recorded state, without `__init__`), calls the real
                   function and asserts the recorded outcome exactly (value or exception
                   class; for a `#post` statement also the receiver's state after the call).
  hypothesis test  one per statement whose binders are all Int/Nat/Bool/String: `@given`
                   over the typed binders, `assume(pre)`, `assert post`, with `pre`/`post`
                   translated to Python by `pyprop`. The translation is accepted only if it
                   agrees with Lean's evaluation on every concrete point that has a real
                   outcome, and at least one of those points satisfied `pre`.

Every test's docstring carries the English property, the statement and function, the
evidence level (kernel-proved, or bounded over N points), the run id, the model name and
the formalize prompt hash. The emitted files are then run with the real interpreter
(`AUTOFORM_PYTHON`, else this one) and the result of every test is recorded in
`emit.json`; a failing emitted test is a finding of this stage (status FAILING), never
dropped. Refuted, uncheckable and unelaborated statements are listed by name with the
reason they were not emitted.

Deduplication: the target's own suite (`<target>/tests`, `<target>/test`, and every
`--tests DIR`) is traced the way the model stage traces it (`model.trace_tests`, no
per-function cap), and a concrete test whose argument tuple the suite already produced is
not emitted; the count is recorded per statement and in total. The generated directory is
removed before tracing so a previous emission never deduplicates itself.

What this stage does NOT do: it never invents an outcome (a point with no faithful
CPython encoding is counted, not guessed), it never emits a test for a point outside the
precondition, and the numbers it reports are counts of tests that ran, not of properties
the model wrote.
"""
from __future__ import annotations

import builtins
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time
import xml.etree.ElementTree as ET
from dataclasses import asdict
from pathlib import Path

from ..harness.verifier import run_lean
from . import check as K
from . import pyprop
from . import pyvalues as pv
from . import schema

LEAN_TIMEOUT = 900
PYTEST_TIMEOUT = 1800
HYPOTHESIS_EXAMPLES = 100
GENERATED_DIR = 'tests/autoform_generated'
MARKER = 'Generated by autoform autoformalize (emit stage)'
SURVIVES = 'BOUNDED_HOLDS'
SUBJECT_PYTHON = os.environ.get('AUTOFORM_PYTHON') or sys.executable
STRATEGY = {'int': 'st.integers()', 'nat': 'st.integers(min_value=0)', 'bool': 'st.booleans()', 'str': '_TEXT'}


def _d(x) -> dict:
    return asdict(x) if hasattr(x, '__dataclass_fields__') else dict(x)


def run_id(run_info: dict | None) -> str:
    """A short stable id of the run: run.json's `id`, else a digest of source, module and start time."""
    info = run_info or {}
    if info.get('id'):
        return str(info['id'])
    return hashlib.sha256(json.dumps([info.get('source'), info.get('module'), info.get('started')]).encode()).hexdigest()[:12]


# ---------------------------------------------------------------- survivors

def survivors(statements: list, checks: list, adjudication: dict | None) -> tuple:
    """([(statement, check, origin)], {statement id: reason not emitted})."""
    checks_by = {c['statement']: c for c in (checks or [])}
    adj = adjudication or {}
    lineage = adj.get('lineage') or {}
    repaired_from: dict = {}
    for rid, lin in lineage.items():
        repaired_from.setdefault(lin.get('parent'), []).append(rid)
    pool = [(s, 'check') for s in statements] + [(s, 'repair') for s in adj.get('statements') or []]
    for c in adj.get('checks') or []:
        checks_by.setdefault(c['statement'], c)
    keep, dropped = [], {}
    for st, origin in pool:
        sid = st['id']
        c = checks_by.get(sid)
        if not st.get('elaborates'):
            dropped[sid] = 'the statement did not elaborate'
            continue
        if c is None:
            dropped[sid] = 'no check result for the statement'
            continue
        status = c.get('status')
        if status == SURVIVES:
            keep.append((st, c, origin))
            continue
        why = {'REFUTED_MODEL': 'refuted by the check stage on the model (kernel-certified counterexample)',
               'REFUTED_RUNTIME': 'refuted by the check stage on a real execution',
               'UNCHECKABLE': 'not checkable', 'ERROR': 'check error'}.get(status, f'check status {status}')
        ce = (c.get('counterexample') or {}).get('inputs')
        if ce:
            why += ' at ' + json.dumps(ce, default=str)[:160]
        elif c.get('detail'):
            why += ': ' + c['detail'].split(';')[0][:160]
        if repaired_from.get(sid):
            why += '; repaired as ' + ', '.join(repaired_from[sid])
        dropped[sid] = why
    return keep, dropped


# ---------------------------------------------------------------- Python literals

def py_literal(t) -> str:
    """Python source for a pyvalues tag (objects as `_obj(...)`, exact floats)."""
    k = t[0]
    if k == 'n':
        return 'None'
    if k == 'b':
        return 'True' if t[1] else 'False'
    if k == 'i':
        return str(int(t[1]))
    if k == 'f':
        x = pv.bits_float(int(t[1]))
        if x != x:
            return "float('nan')"
        if x in (float('inf'), float('-inf')):
            return f"float('{x}')"
        return repr(x)
    if k == 's':
        return repr(t[1])
    if k == 'y':
        return repr(bytes.fromhex(t[1]))
    if k == 't':
        items = [py_literal(x) for x in t[1]]
        return '(' + ', '.join(items) + (',)' if len(items) == 1 else ')')
    if k == 'l':
        return '[' + ', '.join(py_literal(x) for x in t[1]) + ']'
    if k == 'd':
        return '{' + ', '.join(f'{py_literal(a)}: {py_literal(b)}' for a, b in t[1]) + '}'
    if k == 'S':
        body = ', '.join(py_literal(x) for x in pv.set_elems(t))
        if t[2] == 'frozenset':
            return f'frozenset({{{body}}})' if body else 'frozenset()'
        return '{' + body + '}' if body else 'set()'
    if k == 'F':
        if isinstance(getattr(builtins, t[1], None), type):
            return t[1]
        raise ValueError(f'not a builtin type: {t[1]}')
    if k == 'O':
        attrs = '{' + ', '.join(f'{a!r}: {py_literal(x)}' for a, x in t[2]) + '}'
        types = t[3] if len(t) > 3 and t[3] else None
        return f'_obj({t[1]!r}, {attrs}' + (f', {types!r})' if types else ')')
    raise ValueError(f'bad tag {t!r}')


def outcome_literal(desc: dict) -> str:
    """Python source of the `_call` outcome the runner recorded."""
    if desc.get('k') == 'ok':
        return f"('ok', {py_literal(desc['v'])})"
    if desc.get('k') == 'exn':
        return f"('exn', {desc['t']!r})"
    raise ValueError('no literal for ' + str(desc.get('k')))


class _Standin:
    """A stand-in for an object of the target's classes while the stage evaluates the
    Python form of a statement in its own process (only `__dict__` is inspected)."""


def _standin(name: str):
    return type(name.rsplit('.', 1)[-1], (_Standin,), {'__qualname__': name})


def outcome_value(desc: dict):
    """The outcome as the emitted tests see it, with stand-in objects."""
    if desc.get('k') == 'ok':
        return ('ok', pv.untag(desc['v'], _standin))
    return ('exn', desc.get('t'))


# ---------------------------------------------------------------- call targets

def call_target(fn: dict, local: str) -> str:
    """Python source of the callable for `_call`, with `_m` the function's module."""
    kind = fn.get('kind') or 'function'
    parts = local.split('.')
    if kind == 'constructor':
        return '_m.' + '.'.join(parts[:-1])
    if kind == 'property':
        return f"_fget(_m.{'.'.join(parts[:-1])}, {parts[-1]!r})"
    return '_m.' + local


def module_of(translation: dict, fn: dict) -> tuple:
    """(dotted module or None, import root, file stem) of the function's source file."""
    from . import model as M
    root = Path(translation.get('source_root', '')).resolve()
    path = (root / fn['file']).resolve()
    import_root, dotted = M._package_info(root, path)
    return dotted, import_root, path.stem


def test_file_name(dotted: str | None, stem: str) -> str:
    base = (dotted or stem).replace('.', '_')
    return f'test_{base}.py'


# ---------------------------------------------------------------- Lean evaluation of pre/post

def eval_blocks(plans: list) -> list:
    out = []
    for p in plans:
        if not p.rt_rows():
            continue
        t, qa = p.tag, p.args_of('q.1')
        pre, post = p.app('pre_' + t, qa), p.app('post_' + t, qa)
        defs = p.defs() + p.rt_def()
        chk = (f'#eval IO.println ("AUTOFORM_EMIT {t} " ++ toString ((rt_{t}).map '
               f'(fun q => ({pre}, {post} q.2))))')
        out.append((t, defs, chk + '\n'))
    return out


def parse_eval(output: str, tag: str, n: int):
    """[(pre, post)] for the tag's rows, or None when Lean produced no (complete) result."""
    m = re.search(rf'^AUTOFORM_EMIT {re.escape(tag)} (.*)$', output, re.M)
    if not m:
        return None
    rows = re.findall(r'\((true|false), (true|false)\)', m.group(1))
    if len(rows) != n:
        return None
    return [(a == 'true', b == 'true') for a, b in rows]


def evaluate_rows(translation: dict, plans: list, work: Path, lean_root: Path, stem: str) -> dict:
    """{statement id: [(pre, post)] aligned with plan.rt_rows(), or an error string}."""
    blocks = eval_blocks(plans)
    results = {p.id: [] for p in plans}
    if not blocks:
        return results
    text, _ = K.assemble(translation, blocks)
    f = work / f'{stem}_emit.lean'
    f.write_text(text)
    code, out, secs = run_lean(lean_root, f, LEAN_TIMEOUT)
    for p in plans:
        n = len(p.rt_rows())
        if n == 0:
            continue
        if code == 124:
            results[p.id] = f'Lean exceeded {LEAN_TIMEOUT}s evaluating pre/post on the real outcomes ({f})'
            continue
        rows = parse_eval(out, p.tag, n)
        if rows is None:
            errs = K.errors_by_line(out, f)
            results[p.id] = ('Lean evaluation of pre/post produced no result'
                             + (': ' + errs[0][1][:300] if errs else f' (exit {code}): ' + out[-300:]))
        else:
            results[p.id] = rows
    return results


# ---------------------------------------------------------------- tracing the existing suite

def trace_suite(translation: dict, names: set, tests, work: Path) -> tuple:
    """({function name: {argument-tuple key}}, stats) for the target's own tests."""
    from . import model as M
    root = Path(translation.get('source_root', '')).resolve()
    dirs = M._test_dirs(root, tests)
    if not dirs:
        return {}, {'note': 'no test directory to trace', 'dirs': []}
    try:
        fns, _ = M._discover(root, tests=tests)
    except (OSError, SyntaxError, ValueError) as exc:
        return {}, {'error': f'discovery failed: {exc!r}', 'dirs': [str(d) for d in dirs]}
    wanted = [f for f in fns if f.info.name in names]
    classes = sorted({f.get('receiver') for f in translation.get('functions', [])
                      if f.get('receiver') and f.get('kind') != 'static'})
    records, stats = M.trace_tests(wanted, root, dirs, work, classes=classes, limit=10 ** 6)
    keys = {name: {point_key(p) for p in pts} for name, pts in records.items()}
    stats = {k: v for k, v in stats.items() if k not in ('states', 'nested', 'log_tail')}
    stats['dirs'] = [str(d) for d in dirs]
    stats['tuples'] = sum(len(v) for v in keys.values())
    return keys, stats


def point_key(tags: list) -> tuple:
    return tuple(pv.canon(t) for t in tags)


# ---------------------------------------------------------------- the test files

HEADER = '''"""{marker}.

Do not edit: regenerated by every run of the emit stage. Each test states one property a
language model wrote about this code, in the form the autoformalizer verified: a concrete
test replays an argument tuple of the bounded check and asserts the outcome CPython
produced there (which Lean confirmed satisfies the property); a hypothesis test states the
property itself over typed arguments. The docstrings carry the provenance: the English
property, the statement, the evidence, the run id, the model and the formalize prompt hash.

Run: {run_id}. Model: {model}. Source: {source}.
"""
import importlib as _il

import pytest  # noqa: F401
{runtime}

_m = _il.import_module({dotted!r})
'''

HYPOTHESIS_HEADER = '''
hypothesis = pytest.importorskip('hypothesis')
from hypothesis import HealthCheck, assume, given, settings  # noqa: E402
from hypothesis import strategies as st  # noqa: E402

_TEXT = st.text(alphabet=st.characters(exclude_categories=('Cs',)))
_SETTINGS = settings(max_examples={examples}, deadline=None, database=None, derandomize=True,
                     suppress_health_check=[HealthCheck.filter_too_much, HealthCheck.too_slow])
'''


def docstring(english: str, sid: str, fn_name: str, evidence: str, rid: str, model: str, prompt_hash: str) -> str:
    text = (english or '').strip().replace('\\', '\\\\').replace('"""', "'''")
    lines = [text, '', f'statement {sid} about {fn_name}; {evidence}',
             f'autoform run {rid}; model {model}; prompt {prompt_hash or "hash not recorded"}']
    body = [lines[0]] + [('    ' + ln) if ln else '' for ln in lines[1:]]
    return '    """' + '\n'.join(body) + '\n    """'


def concrete_test(name: str, doc: str, binders: list, tags: list, target: str, desc: dict, post_entry: bool) -> str:
    lines = [f'def {name}():', doc]
    args = []
    for b, t in zip(binders, tags):
        var = pyprop.pyname(b['name'])
        lines.append(f'    {var} = {py_literal(t)}')
        args.append(var)
    lines.append(f'    r = _call({target}{"".join(", " + a for a in args)})')
    lines.append(f'    assert _eq(r, {outcome_literal(desc)})')
    if post_entry and desc.get('k') == 'ok' and 'post' in desc and args:
        state = '{' + ', '.join(f'{a!r}: {py_literal(x)}' for a, x in desc['post'][2]) + '}'
        lines.append(f'    assert _eq(_state({args[0]}), {state})')
    return '\n'.join(lines) + '\n'


def hypothesis_test(name: str, doc: str, binders: list, kinds: list, target: str, pre_py: str, post_py: str) -> str:
    given = ', '.join(f'{pyprop.pyname(b["name"])}={STRATEGY[k]}' for b, k in zip(binders, kinds))
    params = ', '.join(pyprop.pyname(b['name']) for b in binders)
    lines = [f'@given({given})', '@_SETTINGS', f'def {name}({params}):', doc]
    if pre_py not in ('True', '(True)'):
        lines.append(f'    assume({pre_py})')
    lines.append(f'    r = _call({target}{"".join(", " + pyprop.pyname(b["name"]) for b in binders)})')
    lines.append(f'    assert {post_py}')
    return '\n'.join(lines) + '\n'


def rebuilt_prompt_hash(translation: dict, fn: dict, st: dict, english) -> str:
    """For runs that predate Statement.prompt_hash: the key of the formalize prompt rebuilt
    from the run's own inputs (marked as rebuilt), or '' when that is not possible."""
    from . import formalize, llm
    for spec in english or []:
        spec = _d(spec)
        if spec.get('function') != st.get('function'):
            continue
        for prop in spec.get('properties') or []:
            prop = _d(prop)
            if prop.get('id') == st.get('property'):
                try:
                    base = formalize.build_prompt(translation, fn, spec, prop)
                except Exception:  # noqa: BLE001 - provenance only; never blocks emission
                    return ''
                return llm.prompt_key(base + llm.json_suffix(['binders', 'pre', 'post'])) + ' (rebuilt)'
    return ''


def evidence_text(check: dict, proof: dict | None) -> str:
    if proof and proof.get('status') == 'PROVED':
        return 'kernel-proved for all inputs (prove stage)'
    return (f"bounded check: kernel-certified over {check.get('domain_size', 0)} domain points, "
            f"real executions agreed")


def clean_generated(target: Path) -> int:
    """Remove the files a previous emission wrote (ours by marker); return how many."""
    if not target.is_dir():
        return 0
    n = 0
    for f in sorted(target.glob('*.py')):
        try:
            head = f.read_text(errors='replace')[:400]
        except OSError:
            continue
        if MARKER in head:
            f.unlink()
            n += 1
    shutil.rmtree(target / '__pycache__', ignore_errors=True)
    return n


# ---------------------------------------------------------------- running the emitted tests

def run_pytest(python: str, target: Path, import_root: Path, work: Path) -> dict:
    """Run the generated directory with the real interpreter; per-test results from JUnit XML."""
    xml = work / 'junit.xml'
    xml.unlink(missing_ok=True)
    cmd = [python, '-m', 'pytest', str(target), '-q', '-p', 'no:cacheprovider', '--no-header',
           f'--junit-xml={xml}', '-o', 'junit_family=xunit2', '-o', 'junit_logging=no']
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE='1', PYTHONHASHSEED='0',
               PYTHONPATH=str(import_root) + (os.pathsep + os.environ['PYTHONPATH'] if os.environ.get('PYTHONPATH') else ''))
    started = time.time()
    try:
        proc = subprocess.run(cmd, cwd=str(import_root), env=env, capture_output=True, text=True,
                              timeout=PYTEST_TIMEOUT, start_new_session=True)
        code, log = proc.returncode, (proc.stdout + proc.stderr)
    except subprocess.TimeoutExpired as exc:
        code, log = 124, f'pytest exceeded {PYTEST_TIMEOUT}s\n' + str(exc.stdout or '')[-1500:]
    rec = {'command': cmd, 'cwd': str(import_root), 'returncode': code, 'seconds': round(time.time() - started, 2),
           'log_tail': log[-2500:], 'tests': {}, 'file_skips': {}}
    if not xml.is_file():
        rec['error'] = 'pytest produced no JUnit report (is pytest importable by ' + python + '?)'
        return rec
    try:
        root = ET.parse(xml).getroot()
    except ET.ParseError as exc:
        rec['error'] = f'unreadable JUnit report: {exc}'
        return rec
    totals = {'tests': 0, 'failures': 0, 'errors': 0, 'skipped': 0}
    for suite in root.iter('testsuite'):
        for k in totals:
            totals[k] += int(suite.get(k) or 0)
    rec['totals'] = totals
    for case in root.iter('testcase'):
        name, cls = case.get('name') or '', case.get('classname') or ''
        status, detail = 'passed', ''
        for child in case:
            if child.tag in ('failure', 'error', 'skipped'):
                status = 'failed' if child.tag == 'failure' else child.tag
                detail = (child.get('message') or '') or (child.text or '')
                detail = detail.strip()[:600]
        if not cls and name.endswith('.py'):          # a module-level skip (importorskip)
            rec['file_skips'][Path(name).name] = detail
            continue
        rec['tests'][(cls.rsplit('.', 1)[-1], name.split('[')[0])] = (status, detail)
    return rec


# ---------------------------------------------------------------- the stage

def emit(translation: dict, statements: list, checks: list, out_dir: Path, *, proofs=None, adjudication=None,
         english=None, run_info=None, tests=(), target=None, domain_size: int = 64, runtime: bool = True,
         lean_root=None, python: str | None = None, run: bool = True) -> dict:
    """Write the tests, run them, write `out_dir/emit.json`; return its contents."""
    t0 = time.time()
    out_dir = Path(out_dir).resolve()      # Lean runs from the lake root: paths must be absolute
    work = out_dir / 'emit'
    work.mkdir(parents=True, exist_ok=True)
    python = python or SUBJECT_PYTHON
    root = Path(lean_root or translation['lean_root'])
    statements = [_d(s) for s in statements]
    checks = [_d(c) for c in checks or []]
    proofs_by = {p['statement']: p for p in map(_d, proofs or [])}
    model_by = {}
    for spec in english or []:
        spec = _d(spec)
        model_by[spec.get('function')] = spec.get('model') or ''
    default_model = os.environ.get('AUTOFORM_LLM_MODEL') or next(iter(model_by.values()), None) or 'claude-code'
    rid = run_id(run_info)
    fns = {f['name']: f for f in translation.get('functions', [])}
    source_root = Path(translation.get('source_root', '')).resolve()
    target = Path(target).resolve() if target else source_root / GENERATED_DIR
    keep, dropped = survivors(statements, checks, adjudication)
    results: dict = {sid: schema.EmitResult(sid, 'NOT_EMITTED', reason=why) for sid, why in dropped.items()}
    out = {'target': str(target), 'python': python, 'run_id': rid, 'model': default_model,
           'source_root': str(source_root), 'files': [], 'statements': [], 'counts': {}, 'dedupe': {},
           'pytest': None, 'notes': []}

    def finish():
        ordered = [results[s['id']] for s in statements if s['id'] in results]
        ordered += [r for sid, r in results.items() if sid not in {s['id'] for s in statements}]
        out['statements'] = [asdict(r) for r in ordered]
        c = out['counts']
        c['statements'] = len(statements) + len((adjudication or {}).get('statements') or [])
        c['survivors'] = len(keep)
        c['emitted'] = sum(r.status in ('EMITTED', 'FAILING') for r in ordered)
        c['failing'] = sum(r.status == 'FAILING' for r in ordered)
        c['not_emitted'] = sum(r.status == 'NOT_EMITTED' for r in ordered)
        all_tests = [t for r in ordered for t in r.tests]
        c['tests'] = len(all_tests)
        c['tests_concrete'] = sum(t['kind'] == 'concrete' for t in all_tests)
        c['tests_hypothesis'] = sum(t['kind'] == 'hypothesis' for t in all_tests)
        for res in ('passed', 'failed', 'error', 'skipped', 'not_run'):
            c[f'tests_{res}'] = sum(t['result'] == res for t in all_tests)
        c['points_deduplicated'] = sum(r.points_deduplicated for r in ordered)
        c['points_outside_pre'] = sum(r.points_outside_pre for r in ordered)
        c['points_unencodable'] = sum(r.points_unencodable for r in ordered)
        c['hypothesis_withheld'] = sum(1 for r in ordered if r.hypothesis and r.hypothesis != 'emitted'
                                       and not r.hypothesis.startswith('no typed-binder'))
        out['seconds'] = round(time.time() - t0, 2)
        (out_dir / schema.FILES['emit']).write_text(json.dumps(out, indent=1, ensure_ascii=False, default=str))
        return out

    if not keep:
        out['notes'].append('no statement survived the check stage; nothing to emit')
        return finish()
    if (translation.get('language') or '').lower() != 'python':
        for st, _, _ in keep:
            results[st['id']] = schema.EmitResult(st['id'], 'NOT_EMITTED',
                                                  reason=f"emit supports Python only; language is {translation.get('language')!r}")
        return finish()
    if not runtime:
        for st, _, _ in keep:
            results[st['id']] = schema.EmitResult(st['id'], 'NOT_EMITTED',
                                                  reason='real executions disabled (--no-runtime): no outcome to assert')
        out['notes'].append('--no-runtime: the emit stage needs real outcomes; nothing emitted')
        return finish()

    # --- plans (the check stage's domains) and real outcomes
    plans: dict = {}
    groups: dict = {}
    for i, (st, c, origin) in enumerate(keep):
        sid = st['id']
        fn = fns.get(st.get('function'))
        if fn is None:
            results[sid] = schema.EmitResult(sid, 'NOT_EMITTED', reason='function not in the translation')
            continue
        try:
            plan = K.Plan(i, st, fn, translation, domain_size)
        except (ValueError, KeyError) as exc:
            results[sid] = schema.EmitResult(sid, 'NOT_EMITTED', reason=f'no domain: {exc}')
            continue
        r = results[sid] = schema.EmitResult(sid, 'NOT_EMITTED', points=len(plan.points))
        if c.get('domain_size') and c['domain_size'] != len(plan.points):
            out['notes'].append(f"{sid}: domain has {len(plan.points)} points here, {c['domain_size']} in the check "
                                f"stage (--domain-size differs); each emitted point is evaluated anew")
        path, why = K.runtime_target(translation, fn)
        if path is None:
            r.reason = why
            continue
        K.run_runtime(translation, fn, plan, work=work / 'runtime')
        if plan.runtime is None:
            r.reason = 'no real outcomes: ' + (plan.runtime_note or 'runtime runner failed')
            continue
        r.points_unencodable = sum(1 for _, _, lit in plan.runtime if lit is None)
        if not plan.rt_rows():
            r.reason = 'no domain point has a faithful CPython outcome (timeouts or unencodable values)'
            continue
        plans[sid] = (plan, fn, c, origin)
        groups.setdefault(st['function'], []).append(plan)

    # --- Lean: pre/post on every real outcome
    rows: dict = {}
    for k, (fname, group) in enumerate(groups.items()):
        stem = f'f{k}_' + re.sub(r'[^A-Za-z0-9_]', '_', fns[fname].get('source_name') or fname)[:40]
        rows.update(evaluate_rows(translation, group, work, root, stem))

    # --- the target's own suite, for deduplication (our own previous files removed first)
    removed = clean_generated(target)
    if removed:
        out['notes'].append(f'removed {removed} previously generated file(s) from {target}')
    needed = {st['function'] for st, _, _ in keep}
    traced, trace_stats = trace_suite(translation, needed, tests, work / 'trace') if plans else ({}, {})
    out['dedupe'] = {'functions_traced': len(traced), 'tuples_traced': trace_stats.get('tuples', 0),
                     'trace': trace_stats}

    # --- render
    files: dict = {}          # file name -> {'dotted', 'import_root', 'concrete': [...], 'hypothesis': [...]}
    seen_names: set = set()
    import_roots: set = set()
    for sid, (plan, fn, c, origin) in plans.items():
        r = results[sid]
        st = plan.st
        evald = rows.get(sid)
        if isinstance(evald, str) or evald is None:
            r.reason = evald or 'Lean evaluation missing'
            continue
        dotted, import_root, stem = module_of(translation, fn)
        import_roots.add(import_root)
        _, local = K.runtime_target(translation, fn)
        target_expr = call_target(fn, local)
        fname = test_file_name(dotted, stem)
        entry = files.setdefault(fname, {'dotted': dotted or stem, 'import_root': import_root, 'concrete': [], 'hypothesis': []})
        prop = st.get('property') or st['id'].rsplit('__', 1)[-1]
        base = 'test_' + re.sub(r'[^A-Za-z0-9_]', '_', local) + '__' + re.sub(r'[^A-Za-z0-9_]', '_', prop)
        while base in seen_names:
            base += '_'
        seen_names.add(base)
        doc = docstring(st.get('english', ''), sid, st['function'], evidence_text(c, proofs_by.get(sid)), rid,
                        model_by.get(st['function']) or default_model,
                        st.get('prompt_hash') or rebuilt_prompt_hash(translation, fn, st, english))
        binders = [b for b in plan.binders if (b.get('val') or '').strip()]
        post_entry = st.get('entry') == 'post'
        suite_keys = traced.get(st['function'], set())
        rt_by_index = {i: d for i, d, _ in plan.runtime}
        tested = 0
        for row, (pre_ok, post_ok) in zip(plan.rt_rows(), evald):
            idx, _ = row
            point = plan.points[idx]
            if not pre_ok:
                r.points_outside_pre += 1
                continue
            if not post_ok:
                r.tests.append({'name': None, 'file': fname, 'kind': 'concrete', 'point': point, 'result': 'error',
                                'detail': 'pre holds but post fails on the real outcome at this point: the check '
                                          'stage should have refuted this statement (inconsistent run)'})
                continue
            tags = K.python_point(plan, point)
            if tags is None:
                r.points_unencodable += 1
                continue
            if point_key(tags) in suite_keys:
                r.points_deduplicated += 1
                continue
            name = f'{base}__{idx}'
            try:
                src = concrete_test(name, doc, binders, tags, target_expr, rt_by_index[idx], post_entry)
            except ValueError as exc:
                r.points_unencodable += 1
                out['notes'].append(f'{sid} point {idx}: no Python literal ({exc})')
                continue
            entry['concrete'].append(src)
            r.tests.append({'name': name, 'file': fname, 'kind': 'concrete', 'point': point, 'result': 'not_run',
                            'detail': ''})
            tested += 1
        r.points_tested = tested
        # hypothesis: typed binders only, translation checked against Lean on the concrete rows
        kinds = plan.kinds
        if any(k == 'val' for k in kinds) or not binders:
            r.hypothesis = 'no typed-binder property: ' + ('a Val binder has no generator' if binders else 'no binders')
        else:
            r.hypothesis = hypothesis_status(plan, binders, kinds, evald, rt_by_index)
            if r.hypothesis == 'emitted':
                names = [b['name'] for b in binders]
                nat_names = [b['name'] for b, k in zip(binders, kinds) if k == 'nat']
                pre_py = pyprop.translate(st.get('pre') or 'true', names, nat_names)
                post_py = pyprop.translate(st['post'], names, nat_names)
                name = f'{base}__property'
                entry['hypothesis'].append(hypothesis_test(name, doc, binders, kinds, target_expr, pre_py, post_py))
                r.tests.append({'name': name, 'file': fname.replace('.py', '_properties.py'), 'kind': 'hypothesis',
                                'point': None, 'result': 'not_run', 'detail': ''})
        if not r.tests:
            r.reason = ('every point ' + ('is deduplicated against the existing suite' if r.points_deduplicated
                        else 'lies outside the precondition' if r.points_outside_pre else 'has no faithful outcome')
                        + f' ({r.points_deduplicated} deduplicated, {r.points_outside_pre} outside pre, '
                          f'{r.points_unencodable} unencodable); ' + (r.hypothesis or ''))

    # --- write
    written = []
    if any(f['concrete'] or f['hypothesis'] for f in files.values()):
        target.mkdir(parents=True, exist_ok=True)
        # a package: `autoform_generated.test_<module>` cannot collide with a `test_<module>.py`
        # the target's own suite may have (pytest refuses two top-level test modules of one name)
        (target / '__init__.py').write_text('"""' + MARKER + ': the emitted tests of one run."""\n')
    for fname, f in sorted(files.items()):
        head = HEADER.format(marker=MARKER, run_id=rid, model=default_model, source=source_root,
                             runtime=pyprop.RUNTIME.rstrip('\n'), dotted=f['dotted'])
        if f['concrete']:
            (target / fname).write_text(head + '\n\n' + '\n\n'.join(f['concrete']))
            written.append(fname)
        if f['hypothesis']:
            pname = fname.replace('.py', '_properties.py')
            (target / pname).write_text(head + HYPOTHESIS_HEADER.format(examples=HYPOTHESIS_EXAMPLES)
                                        + '\n\n' + '\n\n'.join(f['hypothesis']))
            written.append(pname)
    out['files'] = [str(target / w) for w in written]

    # --- run with the real interpreter
    if written and run:
        import_root = sorted(import_roots, key=lambda p: len(str(p)))[0]
        pt = run_pytest(python, target, import_root, work)
        out['pytest'] = {k: v for k, v in pt.items() if k not in ('tests', 'file_skips')}
        for r in results.values():
            for t in r.tests:
                if not t['name']:
                    continue
                key = (Path(t['file']).stem, t['name'])
                if key in pt['tests']:
                    t['result'], t['detail'] = pt['tests'][key]
                elif t['file'] in pt['file_skips']:
                    t['result'], t['detail'] = 'skipped', 'file skipped: ' + pt['file_skips'][t['file']]
                else:
                    t['result'], t['detail'] = 'not_run', pt.get('error') or 'absent from the JUnit report'
    elif written:
        out['notes'].append('tests written but not run (run=False)')
    for r in results.values():
        if r.tests:
            r.status = 'FAILING' if any(t['result'] in ('failed', 'error') for t in r.tests) else 'EMITTED'
            if any(t['result'] == 'not_run' for t in r.tests) and r.status == 'EMITTED':
                r.status = 'FAILING'
                r.reason = 'emitted tests could not be run: ' + ((out['pytest'] or {}).get('error') or 'see pytest log')
    return finish()


def hypothesis_status(plan, binders, kinds, evald, rt_by_index) -> str:
    """'emitted' when pre/post translate to Python and agree with Lean on every real outcome."""
    st = plan.st
    names = [b['name'] for b in binders]
    nat_names = [b['name'] for b, k in zip(binders, kinds) if k == 'nat']
    try:
        pre_py = pyprop.translate(st.get('pre') or 'true', names, nat_names)
        post_py = pyprop.translate(st['post'], names, nat_names)
    except pyprop.Unsupported as exc:
        return f'pre/post not translatable to Python: {exc}'
    ns: dict = {}
    exec(pyprop.RUNTIME, ns)   # noqa: S102 - our own helper source
    exercised = 0
    for (idx, _), (pre_ok, post_ok) in zip(plan.rt_rows(), evald):
        env = dict(ns)
        for b, k, v in zip(binders, kinds, plan.points[idx]):
            env[pyprop.pyname(b['name'])] = v
        try:
            env['r'] = outcome_value(rt_by_index[idx])
            py_pre = bool(eval(pre_py, env))   # noqa: S307 - generated from a parsed Lean term
            py_post = bool(eval(post_py, env)) if py_pre else None   # noqa: S307
        except Exception as exc:  # noqa: BLE001
            return f'Python form of pre/post raised on a concrete point: {type(exc).__name__}: {exc}'
        if py_pre != pre_ok:
            return f'Python form of pre disagrees with Lean at point {idx} ({plan.points[idx]})'
        if py_pre and py_post != post_ok:
            return f'Python form of post disagrees with Lean at point {idx} ({plan.points[idx]})'
        exercised += py_pre
    if not exercised:
        return 'no concrete point satisfied pre, so the Python form of post was never checked against Lean'
    return 'emitted'


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(prog='python -m autoform.nl.emit',
                                 description='Write the surviving properties of a run as pytest tests of the target.')
    ap.add_argument('run_dir', type=Path)
    ap.add_argument('--emit-dir', type=Path, help='directory for the tests (default <source>/tests/autoform_generated)')
    ap.add_argument('--tests', action='append', default=[], metavar='DIR',
                    help="the target's test directory outside its tree (repeatable), traced for deduplication")
    ap.add_argument('--domain-size', type=int, default=64, help='the check stage\'s --domain-size')
    ap.add_argument('--lean-root', type=Path)
    ap.add_argument('--python', help='interpreter for the code under test (default AUTOFORM_PYTHON)')
    ap.add_argument('--no-run', action='store_true', help='write the tests but do not run them')
    a = ap.parse_args(argv)
    load = lambda k: schema.load(a.run_dir / schema.FILES[k]) if (a.run_dir / schema.FILES[k]).is_file() else None  # noqa
    tr = load('translation')
    if tr is None:
        print(f'no {schema.FILES["translation"]} in {a.run_dir}', file=sys.stderr)
        return 2
    run_info = json.loads((a.run_dir / 'run.json').read_text()) if (a.run_dir / 'run.json').is_file() else {}
    res = emit(tr, load('statements') or [], load('checks') or [], a.run_dir, proofs=load('proofs'),
               adjudication=load('adjudication'), english=load('english'), run_info=run_info,
               tests=[str(Path(t).resolve()) for t in a.tests], target=a.emit_dir, domain_size=a.domain_size,
               lean_root=a.lean_root, python=a.python, run=not a.no_run)
    c = res['counts']
    for r in res['statements']:
        print(f"{r['status']:12} {r['statement']}  tests={len(r['tests'])} dedup={r['points_deduplicated']}"
              + (f"  {r['reason'][:100]}" if r['reason'] else '') + (f"  [hypothesis: {r['hypothesis'][:80]}]" if r['hypothesis'] else ''))
    print(f"\nsurvivors {c['survivors']}/{c['statements']}; emitted {c['emitted']} (failing {c['failing']}); tests "
          f"{c['tests']} (concrete {c['tests_concrete']}, hypothesis {c['tests_hypothesis']}): passed "
          f"{c['tests_passed']}, failed {c['tests_failed']}, error {c['tests_error']}, skipped {c['tests_skipped']}, "
          f"not run {c['tests_not_run']}; points deduplicated {c['points_deduplicated']}, outside pre "
          f"{c['points_outside_pre']}, unencodable {c['points_unencodable']}; hypothesis withheld "
          f"{c['hypothesis_withheld']}")
    print(f"files: {', '.join(res['files']) or 'none'}  ->  {a.run_dir / schema.FILES['emit']}")
    return 1 if c['failing'] else 0


if __name__ == '__main__':
    sys.exit(main())
