"""Report stage: report.json + report.md from the stage outputs of one run directory.

Findings first:
  potential bugs      REFUTED_MODEL on a validated model (or on the deep translation)
                      whose English came from documentation or tests — the code disagrees
                      with what its docs/tests say;
  model defects       REFUTED_RUNTIME only: the statement holds on the model over the
                      domain but fails on a real execution, so the model and the program
                      disagree — a defect of the model/translation, not a bug report;
  other refutations   English read off the implementation alone (likely mis-formalized),
                      or refuted on a model that did not validate.

With a judge (selection.json / adjudication.json present) the finding rule is the
cross-validated one: a refuted statement is a potential bug only if the judge read the
counterexample as REAL_BUG, the property has evidence other than the implementation, and
its intent is confident (autoform.nl.repair). REAL_BUG without that support is a suspected
bug; INCOMPLETE_MODEL readings join the model defects; BAD_SPEC / MISSING_PRECONDITION
readings are listed with their repair lineage. Each statement shows the judge's reading,
and each function the properties skipped for budget. The judge never sets a status.

Every function carries a trust level and every statement inherits one:
  L1    the model is proved equal to the deep translation (refine.json) at the
        statement's argument shape;
  L0    the model agreed with the real code on its tests and with a second translation;
  deep  the statement is about the deep translation itself (--deep);
  none  no validated model.
"""
from __future__ import annotations

import json
import re
from dataclasses import asdict
from pathlib import Path

from .schema import FILES

TRUST = (
    "Trust statement. The English descriptions and the Lean statements were generated by a "
    "language model and are untrusted: a statement may not say what its English says. Whether a "
    "statement holds is decided by the Lean kernel — PROVED means the kernel checked a proof of "
    "exactly that statement (axioms listed); BOUNDED_HOLDS means it holds on the finite domain "
    "checked, not in general; REFUTED_MODEL means the kernel found an input where the translated "
    "program violates it. Agreement with real executions (CPython or the native runtime) is "
    "evidence that the translation is faithful, not proof. All proofs are about the translated "
    "program (a Lean model of the code), not about the source code directly; they transfer "
    "to the source only as far as the translation is faithful. Each result carries the trust "
    "level of the model it is about. L0: proved about an AI-written Lean model that agreed with "
    "the real code on every one of N tested inputs and with an independent second translation — "
    "evidence, not proof, of fidelity. L1: the model is additionally proved (by the kernel) equal "
    "to the deep Joern → Core translation run by the Core interpreter, so the proof holds of the "
    "deep translation; fidelity then rests on the deep translator and the interpreter, which are "
    "differentially tested separately. deep: the statement is about the deep translation itself. "
    "none: no validated model; results are about an unvalidated model.")

LEVELS = ('L1', 'L0', 'deep', 'none')
REFUTED = ('REFUTED_MODEL', 'REFUTED_RUNTIME')


def ill_typed(ce) -> bool:
    """The counterexample raised TypeError in the model and, when it ran, in CPython too."""
    ce = ce or {}
    model_te = bool(re.search(r'\.exn\s*\(?\s*(Autoform\.Core\.)?(Val)?\.str\s*"TypeError"', str(ce.get('model', ''))))
    rt = str(ce.get('runtime') or '')
    return model_te and (not rt or rt.strip() == 'raises TypeError')


def _external(evidence) -> list:
    from .judge import external_evidence
    return external_evidence(evidence)


def _d(x):
    return asdict(x) if hasattr(x, '__dataclass_fields__') else dict(x)


def skip_reasons(fn: dict) -> list:
    out = []
    if not fn.get('hole_free', True):
        out.append('untranslated constructs (holes)')
    if not fn.get('call_closed', True):
        out.append('calls untranslated functions')
    return out


def _shape(stmt: dict):
    from .refine import statement_shape
    return statement_shape(stmt)


def _lineage(sid: str, lineage: dict) -> list:
    chain, seen = [sid], {sid}
    while (lineage.get(chain[0]) or {}).get('parent') and lineage[chain[0]]['parent'] not in seen:
        chain.insert(0, lineage[chain[0]]['parent'])
        seen.add(chain[0])
    return chain


def budget_summary(run_info: dict, selection: dict, budget: dict, proofs_by: dict) -> dict:
    stages = (run_info or {}).get('stages') or {}
    skipped = {'selection': [dict(function=r['function'], property=r['property'], reason=r['skip_reason'])
                             for r in (selection or {}).get('properties', []) if not r.get('selected')]}
    for sk in (budget or {}).get('skipped', []):
        skipped.setdefault(sk.get('stage', '?'), []).append(sk)
    skipped['prove'] = [dict(statement=k, reason=p.get('reason', '')[:120]) for k, p in proofs_by.items()
                        if str(p.get('reason', '')).startswith('budget exhausted')]
    return dict(budget_usd=(run_info or {}).get('budget_usd', (selection or {}).get('budget_usd')),
                spent_usd=round(sum((v.get('cost_usd') or 0) + (v.get('earlier_cost_usd') or 0)
                                    for v in stages.values()), 4), planned_usd=(selection or {}).get('planned_usd'),
                estimates=(selection or {}).get('estimates'),
                by_stage={k: round((v.get('cost_usd') or 0) + (v.get('earlier_cost_usd') or 0), 4)
                          for k, v in stages.items() if v.get('cost_usd') is not None},
                skipped={k: v for k, v in skipped.items() if v})


def build(translation, english, statements, checks, proofs, *, run_info=None, functions=None,
          models=None, refine=None, deep_translation=None, selection=None, adjudication=None,
          budget=None) -> dict:
    adj = _d(adjudication or {})
    judged = bool(adj.get('records') is not None and adj) or bool(selection)
    statements = list(statements or []) + list(adj.get('statements') or [])
    checks = list(checks or []) + list(adj.get('checks') or [])
    lineage = adj.get('lineage') or {}
    records = {r['statement']: r for r in adj.get('records') or []}
    sel_rows = {r['statement']: r for r in (selection or {}).get('properties', [])}
    repaired_props = {(p['function'], p['id']): p for p in adj.get('properties') or []}
    suspected, adjudicated = [], []
    translation = _d(translation or {})
    fns = [_d(f) for f in translation.get('functions', [])]
    specs = {e['function']: e for e in map(_d, english or [])}
    checks_by = {c['statement']: c for c in map(_d, checks or [])}
    proofs_by = {p['statement']: p for p in map(_d, proofs or [])}
    stmts = [_d(s) for s in statements or []]
    props = {(e['function'], p['id']): _d(p) for e in specs.values() for p in e.get('properties', [])}
    props.update(repaired_props)
    models_by = {m['function']: m for m in map(_d, models or [])}
    refine_by = {r['function']: r for r in map(_d, refine or [])}
    modelled = bool(models_by)
    deep_tr = _d(deep_translation or {})

    skipped: dict = {}
    out_fns, bugs, defects, mismatches, unvalidated = [], [], [], [], []
    by_fn: dict = {}
    for s in stmts:
        by_fn.setdefault(s['function'], []).append(s)
    for fn in fns:
        reasons = skip_reasons(fn)
        if functions and fn['name'] not in functions and fn.get('source_name') not in functions:
            reasons = ['not selected']
        m, l1 = models_by.get(fn['name']), refine_by.get(fn['name'])
        if modelled:
            if m is None:
                reasons = reasons + ['no model']
            elif m.get('status') != 'VALIDATED':
                reasons = reasons + [f"model {str(m.get('status', '?')).lower()}"]
        for r in reasons:
            skipped[r] = skipped.get(r, 0) + 1
        if not modelled:
            level = 'deep' if translation else 'none'
        elif m is None:
            level = 'none'
        else:
            level = 'L1' if (l1 or {}).get('level') == 'L1' else (m.get('level') or 'none')
            if level == 'L1' and m.get('level') not in ('L0', 'L1'):
                level = 'none'      # never promote a model that did not validate
        proved_shapes = {tuple(sh['kinds']) for sh in (l1 or {}).get('shapes', []) if sh.get('status') == 'PROVED'}
        model_info = None
        if m is not None:
            model_info = {k: m.get(k) for k in ('lean_name', 'signature', 'status', 'tests_run', 'second_translation',
                                                'repairs', 'notes')}
            model_info['disagreements'] = len(m.get('disagreements') or [])
            model_info['disagreement_examples'] = (m.get('disagreements') or [])[:3]
            model_info['level'] = level
        spec = specs.get(fn['name'], {})
        entries = []
        for s in by_fn.get(fn['name'], []):
            c, p = checks_by.get(s['id'], {}), proofs_by.get(s['id'], {})
            prop = props.get((fn['name'], s.get('property')), {})
            # A statement inherits L1 when the model equality is proved at ITS argument shape
            # (even if another shape of the function failed); otherwise it stays at L0.
            if level in ('L0', 'L1') and proved_shapes:
                trust = 'L1' if _shape(s) in proved_shapes else 'L0'
            else:
                trust = level
            entry = {
                'id': s['id'], 'property': s.get('property'), 'kind': prop.get('kind', ''),
                'english': s.get('english') or prop.get('text', ''), 'evidence': prop.get('evidence', []),
                'lean': s.get('lean_prop', ''), 'elaborates': bool(s.get('elaborates')), 'trust': trust,
                'check': {k: c.get(k) for k in ('status', 'domain_size', 'counterexample', 'runtime_agrees',
                                                'kernel_bounded_proof', 'detail')} if c else None,
                'proof': {k: p.get(k) for k in ('status', 'certificate', 'axioms', 'reason', 'seconds', 'cost_usd')}
                if p else None,
            }
            if judged:
                row, rec = sel_rows.get(s['id']) or {}, records.get(s['id']) or {}
                entry['judge'] = {k: row.get(k) for k in ('utility', 'priority', 'order', 'selection_probability',
                                                          'intent')} if row else None
                if row:
                    entry['judge']['judgment'] = (row.get('judgment') or {}).get('label')
                entry['adjudication'] = {k: rec.get(k) for k in (
                    'classification', 'allowed', 'forced', 'margin', 'facts', 'disposition', 'cross_validation',
                    'repair', 'repaired_by', 'model_defect', 'round', 'decision')} if rec else None
                entry['parent'] = (lineage.get(s['id']) or {}).get('parent')
                entry['lineage'] = _lineage(s['id'], lineage) if entry['parent'] else []
            entries.append(entry)
            if c.get('status') in REFUTED:
                item = dict(function=fn['name'], source_name=fn.get('source_name'), file=fn.get('file'),
                            line=fn.get('line'),
                            **{k: entry[k] for k in ('id', 'english', 'evidence', 'lean', 'trust')},
                            status=c['status'], counterexample=c.get('counterexample'))
                validated = not modelled or (m or {}).get('status') == 'VALIDATED'
                rec = records.get(s['id']) if judged else None
                if rec:
                    item.update(classification=rec.get('classification'), disposition=rec.get('disposition'),
                                cross_validation=rec.get('cross_validation'), model_defect=rec.get('model_defect'),
                                repair=rec.get('repair'), repaired_by=rec.get('repaired_by'),
                                parent=entry.get('parent'))
                if rec and validated and c['status'] == 'REFUTED_MODEL':
                    disp = rec.get('disposition')
                    # The judge may repair a spec, but it may not hide that the code contradicts
                    # behaviour the docs or tests state: such a refutation is always listed.
                    # An input the code rejects as ill-typed (TypeError in the model and in
                    # CPython) is outside what the docs describe: it contradicts nothing.
                    documented = bool(_external(entry.get('evidence'))) and not ill_typed(c.get('counterexample'))
                    if disp not in ('finding', 'suspected_bug', 'model_defect') and documented:
                        item['documented_intent_contradicted'] = True
                        disp = 'suspected_bug'
                    (bugs if disp == 'finding' else suspected if disp == 'suspected_bug'
                     else defects if disp == 'model_defect' else adjudicated).append(item)
                elif judged and not rec and validated and c['status'] == 'REFUTED_MODEL':
                    adjudicated.append(dict(item, disposition='not adjudicated'))
                elif c['status'] == 'REFUTED_RUNTIME':
                    defects.append(item)
                elif not validated:
                    unvalidated.append(item)
                elif _external(entry['evidence']):
                    bugs.append(item)
                else:
                    mismatches.append(item)
        l1_info = None
        if l1:
            l1_info = {k: l1.get(k) for k in ('status', 'level', 'deep_function', 'reason', 'cost_usd')}
            keep = ('kinds', 'theorem', 'statement', 'status', 'certificate', 'axioms', 'reason', 'bounded')
            l1_info['shapes'] = [{k: sh.get(k) for k in keep} for sh in l1.get('shapes', [])]
        budget_skips = [dict(property=r['property'], english=r['text'], reason=r['skip_reason'], stage='selection',
                             utility=r.get('utility'))
                        for r in (selection or {}).get('properties', [])
                        if r['function'] == fn['name'] and not r.get('selected')]
        budget_skips += [dict(sk, english=props.get((fn['name'], sk.get('property')), {}).get('text', ''))
                         for sk in (budget or {}).get('skipped', []) if sk.get('function') == fn['name']]
        out_fns.append({'budget_skips': budget_skips if judged else [],
                        'name': fn['name'], 'source_name': fn.get('source_name'), 'file': fn.get('file'),
                        'line': fn.get('line'), 'eligible': not reasons, 'skipped': reasons, 'level': level,
                        'model': model_info, 'l1': l1_info,
                        'summary': spec.get('summary', ''), 'properties': entries})
    # statements for functions the translation does not list (should not happen) are kept
    known = {f['name'] for f in fns}
    for name, ss in by_fn.items():
        if name not in known:
            out_fns.append({'name': name, 'eligible': None, 'skipped': ['not in translation'], 'summary': '',
                            'level': 'none', 'model': None, 'l1': None,
                            'properties': [{'id': s['id'], 'english': s.get('english'), 'lean': s.get('lean_prop'),
                                            'trust': 'none'} for s in ss]})

    status = [(checks_by.get(s['id']) or {}).get('status') for s in stmts]
    by_level = {}
    for f in out_fns:
        lv = by_level.setdefault(f['level'], {'functions': 0, 'statements': 0, 'bounded_holds': 0, 'proved': 0})
        lv['functions'] += 1
    for f in out_fns:
        for e in f['properties']:
            lv = by_level.setdefault(e['trust'], {'functions': 0, 'statements': 0, 'bounded_holds': 0, 'proved': 0})
            lv['statements'] += 1
            lv['bounded_holds'] += (e.get('check') or {}).get('status') == 'BOUNDED_HOLDS'
            lv['proved'] += (e.get('proof') or {}).get('status') == 'PROVED'
    by_level = {k: by_level[k] for k in LEVELS if k in by_level}
    totals = {
        'functions_translated': len(fns),
        'functions_eligible': sum(1 for f in out_fns if f.get('eligible')),
        'functions_skipped': skipped,
        'functions_described': len(specs),
        'properties': sum(len(e.get('properties', [])) for e in specs.values()),
        'statements': len(stmts),
        'statements_elaborated': sum(1 for s in stmts if s.get('elaborates')),
        'bounded_holds': status.count('BOUNDED_HOLDS'),
        'refuted_by_model': status.count('REFUTED_MODEL'),
        'refuted_by_runtime': status.count('REFUTED_RUNTIME'),
        'uncheckable': status.count('UNCHECKABLE'),
        'check_errors': status.count('ERROR'),
        'proved': sum(1 for p in proofs_by.values() if p.get('status') == 'PROVED'),
        'proof_failed': sum(1 for p in proofs_by.values() if p.get('status') == 'FAILED'),
        'proof_budget_skipped': sum(1 for p in proofs_by.values()
                                    if str(p.get('reason', '')).startswith('budget exhausted')),
        'potential_bugs': len(bugs),
        'model_defects': len(defects),
        'models': len(models_by),
        'models_validated': sum(1 for m in models_by.values() if m.get('status') == 'VALIDATED'),
        'l1_attempted': sum(1 for r in refine_by.values() if r.get('shapes')),
        'l1_proved': sum(1 for r in refine_by.values() if r.get('level') == 'L1'),
        'by_level': by_level,
    }
    if judged:
        dispositions: dict = {}
        for r in records.values():
            dispositions[r.get('disposition')] = dispositions.get(r.get('disposition'), 0) + 1
        totals.update(suspected_bugs=len(suspected), repaired_statements=len(adj.get('statements') or []),
                      adjudicated=len(records), dispositions=dispositions,
                      judge=((selection or {}).get('judge') or adj.get('judge') or {}).get('backend'),
                      properties_selected=(selection or {}).get('selected'),
                      properties_skipped=(selection or {}).get('skipped'),
                      decisions=(run_info or {}).get('decisions'))
    return {'module': translation.get('module'), 'language': translation.get('language'),
            'source_root': translation.get('source_root'), 'source_revision': translation.get('source_revision'),
            'call_template': translation.get('call_template'),
            'deep_call_template': deep_tr.get('call_template'),
            'trust': TRUST, 'totals': totals,
            'findings': {'potential_bugs': bugs, 'model_defects': defects,
                         'refuted_implementation_only': mismatches, 'refuted_unvalidated_model': unvalidated,
                         **({'suspected_bugs': suspected, 'refuted_adjudicated': adjudicated} if judged else {})},
            'budget': budget_summary(run_info, selection, budget, proofs_by) if judged else None,
            'functions': out_fns, 'run': run_info or {}}


def _ce(c) -> str:
    ce = (c or {}).get('counterexample')
    if not ce:
        return ''
    parts = [f"inputs `{json.dumps(ce.get('inputs'), ensure_ascii=False)}`"]
    if ce.get('model') is not None:
        parts.append(f"model: `{ce['model']}`")
    if ce.get('runtime') is not None:
        parts.append(f"CPython: `{ce['runtime']}`")
    return '; '.join(parts)


def _model_line(fn: dict) -> str:
    m = fn.get('model')
    if not m:
        return f"level **{fn.get('level')}**" + (' (deep translation)' if fn.get('level') == 'deep' else
                                                  ' (no model)')
    return (f"level **{fn['level']}** — model `{m.get('lean_name')}` : `{m.get('signature')}`, {m.get('status')}; "
            f"agreed with the real code on {m.get('tests_run')} inputs, {m.get('disagreements')} disagreements; "
            f"second translation: {m.get('second_translation')}; repairs: {m.get('repairs')}")


def _l1_line(fn: dict) -> list:
    l1 = fn.get('l1')
    if not l1:
        return []
    if l1.get('level') == 'L1':
        out = [f"- L1: proved equal to the deep translation `{l1.get('deep_function')}` "
               f"({', '.join(sh['theorem'] for sh in l1['shapes'])}); every proof about the model at these argument "
               f"shapes transfers to the deep translation."]
    else:
        out = [f"- L1 not established ({l1.get('status')}): {str(l1.get('reason') or '')[:300]}"]
    for sh in l1.get('shapes', []):
        b = sh.get('bounded') or {}
        at = f" at {b['disagreement']}" if b.get('disagreement') else ''
        out.append(f"  - `{sh['theorem']}` ({', '.join(sh['kinds']) or 'no arguments'}): {sh['status']}; bounded "
                   f"check {b.get('status', 'not run')}{at}")
    return out


def markdown(rep: dict) -> str:
    t = rep['totals']
    md = [f"# Autoformalization report: {rep.get('module') or '?'}", '',
          f"Source: `{rep.get('source_root')}` @ `{rep.get('source_revision')}` ({rep.get('language')})", '',
          '> ' + rep['trust'], '', '## Totals', '',
          f"- functions translated: {t['functions_translated']}; eligible: {t['functions_eligible']}; skipped: "
          + (', '.join(f'{k}: {v}' for k, v in t['functions_skipped'].items()) or 'none'),
          f"- properties described: {t['properties']}; statements: {t['statements']}, "
          f"elaborated: {t['statements_elaborated']}",
          f"- bounded holds: {t['bounded_holds']}; refuted by model: {t['refuted_by_model']}; "
          f"refuted by runtime: {t['refuted_by_runtime']}; uncheckable: {t['uncheckable']}; "
          f"check errors: {t['check_errors']}",
          f"- proved (kernel): {t['proved']}; proof attempts failed: {t['proof_failed']}; "
          f"not attempted (budget): {t.get('proof_budget_skipped', 0)}"]
    if t.get('models'):
        md.append(f"- models: {t['models']}, validated: {t['models_validated']}; L1 attempted: "
                  f"{t['l1_attempted']}, proved: {t['l1_proved']}")
    md.append('')
    if t.get('by_level'):
        md += ['| trust level | functions | statements | bounded holds | proved |', '|---|---|---|---|---|']
        for k, v in t['by_level'].items():
            md.append(f"| {k} | {v['functions']} | {v['statements']} | {v['bounded_holds']} | {v['proved']} |")
        md.append('')
    run = rep.get('run') or {}
    if run.get('stages'):
        md += ['## Stages', '', '| stage | status | seconds | cost (USD) | note |', '|---|---|---|---|---|']
        for name, st in run['stages'].items():
            note = (st.get('error') or '').splitlines()[0][:120] if st.get('error') else st.get('note', '')
            md.append(f"| {name} | {st.get('status')} | {st.get('seconds', '')} | {st.get('cost_usd', '')} | {note} |")
        md.append('')
    b = rep.get('budget')
    if b:
        spent = b.get('spent_usd')
        md += ['## Spent vs budget', '',
               f"- budget: {'$%.2f' % b['budget_usd'] if b.get('budget_usd') is not None else 'none'}; spent: "
               f"${spent or 0:.2f}; planned at selection: ${b.get('planned_usd') or 0:.2f} "
               f"(estimate ${((b.get('estimates') or {}).get('per_property_usd') or 0):.2f} per property)",
               '- by stage: ' + (', '.join(f'{k} ${v}' for k, v in (b.get('by_stage') or {}).items()) or 'n/a')]
        for stage, items in (b.get('skipped') or {}).items():
            md.append(f"- skipped at {stage}: {len(items)}")
            for it in items[:12]:
                md.append(f"  - {it.get('function', '').rsplit('.', 1)[-1]} {it.get('property') or it.get('statement')}: "
                          f"{it.get('reason')}")
        dec = t.get('decisions') or {}
        if dec.get('decisions') is not None:
            md.append(f"- judge ({t.get('judge')}): {dec['decisions']} decisions ({dec['forced']} forced by the "
                      f"gates); JEVBench rows {dec['jevbench_rows']}, labels {dec.get('labels')}")
        md.append('')
    f = rep['findings']
    md += ['## Findings', '']
    judged = 'suspected_bugs' in f
    if f['potential_bugs']:
        md += ['### Potential bugs (' + ('judge: REAL_BUG, cross-validated by evidence other than the implementation '
                                         'and a confident intent' if judged else
                                         'refuted on a validated model; the English came from docs or tests') + ')', '']
        for x in f['potential_bugs']:
            md += [f"- **{x['source_name']}** ({x['file']}:{x['line']}) — {x['status']} [{x.get('trust')}]: "
                   f"{x['english']}",
                   f"  - evidence: {', '.join(map(str, x['evidence']))}",
                   f"  - counterexample: {_ce(x) or 'n/a'}", f"  - Lean: `{x['lean']}`"]
            if x.get('cross_validation'):
                md.append(f"  - cross-validation: {x['cross_validation']}")
        md.append('')
    else:
        md += (['No cross-validated bugs (judge: REAL_BUG with evidence beyond the implementation and a confident '
                'intent). The suspected bugs below still contradict documented behaviour and need review.', '']
               if f.get('suspected_bugs') else
               ['No potential bugs: no refuted statement on a validated model is backed by documentation or tests.', ''])
    if f.get('suspected_bugs'):
        md += ['### Suspected bugs (for review)', '']
        for x in f['suspected_bugs']:
            if x.get('documented_intent_contradicted'):
                why = (f"the docs/tests state this and the code contradicts it (judge read it as "
                       f"{x.get('classification')}"
                       + (f", repaired: {(x.get('repair') or {}).get('text')}" if x.get('repair') else '') + ')')
            else:
                cv = x.get('cross_validation') or {}
                why = ('judge: REAL_BUG, not cross-validated (' +
                       ('no evidence beyond the implementation' if not cv.get('external_evidence')
                        else f"intent not confident: {cv.get('intent')}") + ')')
            md.append(f"- {x['source_name']}: {x['english']} ({_ce(x) or 'no counterexample'}) — {why}")
        md.append('')
    if f.get('model_defects'):
        md += ['### Model defects (the model and the real code disagree; not bug reports)', '']
        for x in f['model_defects']:
            d = x.get('model_defect') or {}
            md.append(f"- {x['source_name']}: {x['english']} ({_ce(x) or 'no counterexample'})"
                      + (f" — {d.get('classification')} in `{d.get('model')}` ({d.get('gate')}; owner: "
                         f"{d.get('owner')})" if d else ''))
        md.append('')
    if f.get('refuted_adjudicated'):
        md += ['### Refuted, adjudicated as not a bug (repair lineage in the function sections)', '']
        for x in f['refuted_adjudicated']:
            r = x.get('repair') or {}
            md.append(f"- {x['source_name']} {x['id']}: {x.get('classification')} → {x.get('disposition')}"
                      + (f" ({r.get('kind')}: {r.get('english') or r.get('text')} → `{x.get('repaired_by')}`)"
                         if x.get('repaired_by') else '') + f" — {x['english']}")
        md.append('')
    if f['refuted_implementation_only']:
        md += ['### Refuted, English read off the implementation (likely mis-formalized)', '']
        for x in f['refuted_implementation_only']:
            md.append(f"- {x['source_name']}: {x['status']} — {x['english']} ({_ce(x) or 'no counterexample'})")
        md.append('')
    if f.get('refuted_unvalidated_model'):
        md += ['### Refuted on a model that did not validate (not evidence about the code)', '']
        for x in f['refuted_unvalidated_model']:
            md.append(f"- {x['source_name']}: {x['status']} — {x['english']} ({_ce(x) or 'no counterexample'})")
        md.append('')
    md += ['## Functions', '']
    for fn in rep['functions']:
        md += [f"### {fn.get('source_name') or fn['name']}", '', f"`{fn['name']}`" +
               (f" — skipped: {', '.join(fn['skipped'])}" if fn.get('skipped') else ''), '',
               '- ' + _model_line(fn)] + _l1_line(fn) + ['']
        if fn.get('summary'):
            md += [fn['summary'], '']
        for p in fn.get('properties', []):
            c, pr = p.get('check') or {}, p.get('proof') or {}
            md += [f"- **{p['id']}** [{p.get('trust')}] {p.get('english', '')}",
                   f"  - Lean: `{p.get('lean', '')}`" + ('' if p.get('elaborates') else ' (does not elaborate)'),
                   f"  - check: {c.get('status', 'not checked')}" +
                   (f" on {c['domain_size']} points" if c.get('domain_size') else '') +
                   (f"; runtime agrees: {c['runtime_agrees']}" if c.get('runtime_agrees') is not None else '') +
                   (f"; counterexample {_ce(c)}" if c.get('counterexample') else ''),
                   f"  - proof: {pr.get('status', 'not attempted')}" +
                   (f" — certificate `{pr['certificate']}`, axioms {pr.get('axioms')}" if pr.get('status') == 'PROVED'
                    else (f" — {pr['reason'][:200]}" if pr.get('reason') else '')),
                   f"  - trust: {p.get('trust')}"]
            md += _judge_lines(p)
        for sk in fn.get('budget_skips') or []:
            md.append(f"- skipped {sk.get('property')} ({sk.get('stage')}): {sk.get('reason')} — {sk.get('english', '')}")
        md.append('')
    return '\n'.join(md) + '\n'


def _judge_lines(p: dict) -> list:
    out = []
    j = p.get('judge')
    if j:
        intent = j.get('intent') or {}
        out.append(f"  - judge: {j.get('judgment')}, utility {j.get('utility')}, order {j.get('order')}"
                   + (f"; intent {'chosen' if intent.get('chosen') else 'rival'} (p={intent.get('probability')})"
                      if intent else ''))
    a = p.get('adjudication')
    if a:
        r = a.get('repair') or {}
        out.append(f"  - counterexample reading: {a.get('classification')}"
                   + (' (forced by the gates)' if a.get('forced') else f" among {', '.join(a.get('allowed') or [])}"
                      f" (margin {a.get('margin')})")
                   + f" → {a.get('disposition')}")
        if r.get('chosen'):
            out.append(f"  - repair: {r.get('chosen')} ({r.get('kind')})"
                       + (f" (margin {r.get('margin')}{', a tie: review' if (r.get('margin') or 0) < 0.02 else ''})"
                          if r.get('margin') is not None else '')
                       + (f": \"{r.get('english')}\"" if r.get('english') else '')
                       + (f" → `{a.get('repaired_by')}`" if a.get('repaired_by') else '')
                       + (f"; {r.get('skipped')}" if r.get('skipped') else ''))
        if a.get('model_defect'):
            out.append(f"  - model defect: {a['model_defect'].get('classification')} in `{a['model_defect'].get('model')}`")
    if p.get('parent'):
        out.append(f"  - repaired from `{p['parent']}` (lineage: {' → '.join(p.get('lineage') or [])})")
    return out


def _load(out: Path, key: str):
    f = out / FILES[key]
    try:
        return json.loads(f.read_text()) if f.is_file() else None
    except ValueError:
        return None


def report(out_dir, *, translation=None, english=None, statements=None, checks=None, proofs=None,
           run_info=None, functions=None, models=None, refine=None, deep_translation=None, selection=None,
           adjudication=None) -> dict:
    """Build from the given stage outputs, or from the JSON files in `out_dir`."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    get = lambda v, k: v if v is not None else _load(out, k)   # noqa: E731
    rep = build(get(translation, 'translation') or {}, get(english, 'english') or [],
                get(statements, 'statements') or [], get(checks, 'checks') or [], get(proofs, 'proofs') or [],
                run_info=run_info, functions=functions, models=get(models, 'models') or [],
                refine=get(refine, 'refine') or [], deep_translation=get(deep_translation, 'deep_translation') or {},
                selection=get(selection, 'selection') or {}, adjudication=get(adjudication, 'adjudication') or {},
                budget=_load(out, 'budget') if selection is None else None)
    (out / FILES['report']).write_text(json.dumps(rep, indent=1, ensure_ascii=False, default=str))
    (out / 'report.md').write_text(markdown(rep))
    return rep
