"""Report stage: report.json + report.md from the stage outputs of one run directory.

Findings first: statements refuted by the model or by the real runtime whose English came
from documentation or tests (anything other than the implementation alone) are potential
bugs — the code disagrees with what its docs/tests say. Refuted statements read off the
implementation itself more likely mean the English or its formalization is wrong.
"""
from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .schema import FILES

TRUST = (
    "Trust statement. The English descriptions and the Lean statements were generated by a "
    "language model and are untrusted: a statement may not say what its English says. Whether a "
    "statement holds is decided by the Lean kernel — PROVED means the kernel checked a proof of "
    "exactly that statement (axioms listed); BOUNDED_HOLDS means it holds on the finite domain "
    "checked, not in general; REFUTED_MODEL means the kernel found an input where the translated "
    "program violates it. Agreement with real executions (CPython or the native runtime) is "
    "evidence that the translation is faithful, not proof. All proofs are about the translated "
    "program (the Lean model `runFunc ...`), not about the source code directly; they transfer "
    "to the source only as far as the translation is faithful.")

REFUTED = ('REFUTED_MODEL', 'REFUTED_RUNTIME')


def _d(x):
    return asdict(x) if hasattr(x, '__dataclass_fields__') else dict(x)


def _external(evidence) -> list:
    return [e for e in evidence or [] if not str(e).lower().startswith('implementation')]


def skip_reasons(fn: dict) -> list:
    out = []
    if not fn.get('hole_free', True):
        out.append('untranslated constructs (holes)')
    if not fn.get('call_closed', True):
        out.append('calls untranslated functions')
    return out


def build(translation, english, statements, checks, proofs, *, run_info=None, functions=None) -> dict:
    translation = _d(translation or {})
    fns = [_d(f) for f in translation.get('functions', [])]
    specs = {e['function']: e for e in map(_d, english or [])}
    checks_by = {c['statement']: c for c in map(_d, checks or [])}
    proofs_by = {p['statement']: p for p in map(_d, proofs or [])}
    stmts = [_d(s) for s in statements or []]
    props = {(e['function'], p['id']): _d(p) for e in specs.values() for p in e.get('properties', [])}

    skipped: dict = {}
    out_fns, findings, mismatches = [], [], []
    by_fn: dict = {}
    for s in stmts:
        by_fn.setdefault(s['function'], []).append(s)
    for fn in fns:
        reasons = skip_reasons(fn)
        if functions and fn['name'] not in functions and fn.get('source_name') not in functions:
            reasons = ['not selected']
        for r in reasons:
            skipped[r] = skipped.get(r, 0) + 1
        spec = specs.get(fn['name'], {})
        entries = []
        for s in by_fn.get(fn['name'], []):
            c, p = checks_by.get(s['id'], {}), proofs_by.get(s['id'], {})
            prop = props.get((fn['name'], s.get('property')), {})
            entry = {
                'id': s['id'], 'property': s.get('property'), 'kind': prop.get('kind', ''),
                'english': s.get('english') or prop.get('text', ''), 'evidence': prop.get('evidence', []),
                'lean': s.get('lean_prop', ''), 'elaborates': bool(s.get('elaborates')),
                'check': {k: c.get(k) for k in ('status', 'domain_size', 'counterexample', 'runtime_agrees',
                                                'kernel_bounded_proof', 'detail')} if c else None,
                'proof': {k: p.get(k) for k in ('status', 'certificate', 'axioms', 'reason', 'seconds', 'cost_usd')}
                if p else None,
            }
            entries.append(entry)
            if c.get('status') in REFUTED:
                item = dict(function=fn['name'], source_name=fn.get('source_name'), file=fn.get('file'),
                            line=fn.get('line'), **{k: entry[k] for k in ('id', 'english', 'evidence', 'lean')},
                            status=c['status'], counterexample=c.get('counterexample'))
                (findings if _external(entry['evidence']) else mismatches).append(item)
        out_fns.append({'name': fn['name'], 'source_name': fn.get('source_name'), 'file': fn.get('file'),
                        'line': fn.get('line'), 'eligible': not reasons, 'skipped': reasons,
                        'summary': spec.get('summary', ''), 'properties': entries})
    # statements for functions the translation does not list (should not happen) are kept
    known = {f['name'] for f in fns}
    for name, ss in by_fn.items():
        if name not in known:
            out_fns.append({'name': name, 'eligible': None, 'skipped': ['not in translation'], 'summary': '',
                            'properties': [{'id': s['id'], 'english': s.get('english'), 'lean': s.get('lean_prop')}
                                           for s in ss]})

    status = [(checks_by.get(s['id']) or {}).get('status') for s in stmts]
    totals = {
        'functions_translated': len(fns),
        'functions_eligible': sum(1 for f in out_fns if f.get('eligible')),
        'functions_skipped': skipped,
        'functions_described': len(specs),
        'properties': sum(len(e.get('properties', [])) for e in specs.values()),
        'statements': len(stmts),
        'statements_elaborated': sum(1 for s in stmts if s.get('elaborates')),
        'bounded_holds': status.count('BOUNDED_HOLDS'),
        'refuted_by_model': status.count('REFUTED_MODEL'),
        'refuted_by_runtime': status.count('REFUTED_RUNTIME'),
        'uncheckable': status.count('UNCHECKABLE'),
        'check_errors': status.count('ERROR'),
        'proved': sum(1 for p in proofs_by.values() if p.get('status') == 'PROVED'),
        'proof_failed': sum(1 for p in proofs_by.values() if p.get('status') == 'FAILED'),
        'potential_bugs': len(findings),
    }
    return {'module': translation.get('module'), 'language': translation.get('language'),
            'source_root': translation.get('source_root'), 'source_revision': translation.get('source_revision'),
            'trust': TRUST, 'totals': totals,
            'findings': {'potential_bugs': findings, 'refuted_implementation_only': mismatches},
            'functions': out_fns, 'run': run_info or {}}


def _ce(c) -> str:
    ce = (c or {}).get('counterexample')
    if not ce:
        return ''
    parts = [f"inputs `{json.dumps(ce.get('inputs'), ensure_ascii=False)}`"]
    if ce.get('model') is not None:
        parts.append(f"model: `{ce['model']}`")
    if ce.get('runtime') is not None:
        parts.append(f"CPython: `{ce['runtime']}`")
    return '; '.join(parts)


def markdown(rep: dict) -> str:
    t = rep['totals']
    md = [f"# Autoformalization report: {rep.get('module') or '?'}", '',
          f"Source: `{rep.get('source_root')}` @ `{rep.get('source_revision')}` ({rep.get('language')})", '',
          '> ' + rep['trust'], '', '## Totals', '',
          f"- functions translated: {t['functions_translated']}; eligible: {t['functions_eligible']}; skipped: "
          + (', '.join(f'{k}: {v}' for k, v in t['functions_skipped'].items()) or 'none'),
          f"- properties described: {t['properties']}; statements: {t['statements']}, "
          f"elaborated: {t['statements_elaborated']}",
          f"- bounded holds: {t['bounded_holds']}; refuted by model: {t['refuted_by_model']}; "
          f"refuted by runtime: {t['refuted_by_runtime']}; uncheckable: {t['uncheckable']}; "
          f"check errors: {t['check_errors']}",
          f"- proved (kernel): {t['proved']}; proof attempts failed: {t['proof_failed']}", '']
    run = rep.get('run') or {}
    if run.get('stages'):
        md += ['## Stages', '', '| stage | status | seconds | cost (USD) | note |', '|---|---|---|---|---|']
        for name, st in run['stages'].items():
            md.append(f"| {name} | {st.get('status')} | {st.get('seconds', '')} | {st.get('cost_usd', '')} | "
                      f"{(st.get('error') or '').splitlines()[0][:120] if st.get('error') else ''} |")
        md.append('')
    f = rep['findings']
    md += ['## Findings', '']
    if f['potential_bugs']:
        md += ['### Potential bugs (refuted; the English came from docs or tests)', '']
        for x in f['potential_bugs']:
            md += [f"- **{x['source_name']}** ({x['file']}:{x['line']}) — {x['status']}: {x['english']}",
                   f"  - evidence: {', '.join(map(str, x['evidence']))}",
                   f"  - counterexample: {_ce(x) or 'n/a'}", f"  - Lean: `{x['lean']}`"]
        md.append('')
    else:
        md += ['No potential bugs: no refuted statement is backed by documentation or tests.', '']
    if f['refuted_implementation_only']:
        md += ['### Refuted, English read off the implementation (likely mis-formalized)', '']
        for x in f['refuted_implementation_only']:
            md.append(f"- {x['source_name']}: {x['status']} — {x['english']} ({_ce(x) or 'no counterexample'})")
        md.append('')
    md += ['## Functions', '']
    for fn in rep['functions']:
        md += [f"### {fn.get('source_name') or fn['name']}", '', f"`{fn['name']}`" +
               (f" — skipped: {', '.join(fn['skipped'])}" if fn.get('skipped') else ''), '']
        if fn.get('summary'):
            md += [fn['summary'], '']
        for p in fn.get('properties', []):
            c, pr = p.get('check') or {}, p.get('proof') or {}
            md += [f"- **{p['id']}** {p.get('english', '')}",
                   f"  - Lean: `{p.get('lean', '')}`" + ('' if p.get('elaborates') else ' (does not elaborate)'),
                   f"  - check: {c.get('status', 'not checked')}" +
                   (f" on {c['domain_size']} points" if c.get('domain_size') else '') +
                   (f"; runtime agrees: {c['runtime_agrees']}" if c.get('runtime_agrees') is not None else '') +
                   (f"; counterexample {_ce(c)}" if c.get('counterexample') else ''),
                   f"  - proof: {pr.get('status', 'not attempted')}" +
                   (f" — certificate `{pr['certificate']}`, axioms {pr.get('axioms')}" if pr.get('status') == 'PROVED'
                    else (f" — {pr['reason'][:200]}" if pr.get('reason') else ''))]
        md.append('')
    return '\n'.join(md) + '\n'


def _load(out: Path, key: str):
    f = out / FILES[key]
    try:
        return json.loads(f.read_text()) if f.is_file() else None
    except ValueError:
        return None


def report(out_dir, *, translation=None, english=None, statements=None, checks=None, proofs=None,
           run_info=None, functions=None) -> dict:
    """Build from the given stage outputs, or from the JSON files in `out_dir`."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    get = lambda v, k: v if v is not None else _load(out, k)   # noqa: E731
    rep = build(get(translation, 'translation') or {}, get(english, 'english') or [],
                get(statements, 'statements') or [], get(checks, 'checks') or [], get(proofs, 'proofs') or [],
                run_info=run_info, functions=functions)
    (out / FILES['report']).write_text(json.dumps(rep, indent=1, ensure_ascii=False, default=str))
    (out / 'report.md').write_text(markdown(rep))
    return rep
