import Autoform.SpecsGen.Basis
import Autoform.Harness.Audit
import Autoform.Generated.PipelineC

/-! Generated by `scripts/synth_specs.py`. Do not edit by hand. -/
namespace Autoform.SpecsGen.PipelineC

open Autoform.Core Autoform.Refine Autoform.SpecsGen

-- The proofs below are by computation on concrete inputs: the kernel walks the
-- interpreter, and deeply nested calls need more than the default budgets.
set_option maxRecDepth 100000
set_option maxHeartbeats 10000000
set_option cbv.warning false
set_option exponentiation.threshold 4096

abbrev P : Program := Autoform.Generated.PipelineC.program

/-- The module-initialiser heap, evaluated once by `initGlobals P 5000 moduleInits` and
frozen into this literal so that the kernel does not re-run the initialisers for every
case of every proof. -/
def h0 : Heap := [{ cls := "<globals>", fields := [], captured := [], payload := Autoform.Core.Payload.none, version := 0 }]

/-- Address of the globals frame. -/
def gref : Ref := 0
def base : Nat := h0.length
def C : Ctx := { dialect := P.dialect, table := P.table, globals := gref,
                 builtinBases := P.builtinBases, properties := P.properties,
                 excClasses := P.excClasses, classDecls := P.classDecls }
def FUEL : Nat := 5000
open Autoform.Generated.PipelineC



/-!
# Synthesized specifications — `PipelineC`

**Generated by `scripts/synth_specs.py`. Do not edit by hand.**

Every statement below is about `Autoform/Generated/PipelineC.lean` *by import*, so a
mutation of the generated module is a mutation of the subject of these theorems
(`scripts/mutate.py --spec-file`). The `#audit_depends` block at the end fails the build
for any theorem that does not mention the implementation it claims to constrain.

What each family claims, in the order of `STRATEGY.md` §4:

* `conform_*` (§4.4, cross-implementation) — the interpreter reproduces, case by case,
  the outcome the **source runtime** produced for the recorded calls to this
  function. The right-hand sides were recorded by `scripts/differential.py`;
  they are not this system's own output, which is what keeps the family from being an
  elaborate `rfl`.
* `runs_*` / `returns_*` (§4.2, structural) — on this domain the interpreter neither
  reaches an untranslated construct nor exhausts its fuel. `EResult` distinguishes
  `.hole` and `.outOfFuel` from behaviour, so this is a real property, and it is stated
  only for functions whose AST *could* violate it.
* `heappure_*`, `const_*`, `projects_*`, `identity_*`, `idempotent_*`, `involutive_*`,
  `commutes_*`, `nonneg_*` (§4.3, algebraic) — laws mined from observed executions and
  **refuted against a fuzzed domain before emission**. Survivors only.
* `uconst_*`, `uproj_*` — universally quantified refinements, proved for every input and
  every fuel budget above a stated bound.

Domains are finite and explicit, and the theorems about them are proved by computation.
That is deliberate: a kernel-checked test is a test whose axiom basis is auditable and
whose subject a mutation gate can attack.

**Fuel.** A law checked at one budget is a weaker claim than it looks, so each law here is
stated as `∀ fuel, FUEL ≤ fuel → …` wherever that could be *proved*: checked at `FUEL` by
computation and transported by `Autoform/FuelMono.lean`'s `applyFunc_fuel_mono`. That
transport needs two side conditions, both discharged rather than assumed — the context is
covered by the unrestricted fuel theorem (including finalizers) and the run did not
end in `outOfFuel` (the `g…` guard, evaluated over the same domain as the law). Where
either fails, the theorem stays at `FUEL` and its generalization is recorded in
`obligations` below as a `Prop`-valued `def` — a statement, not an admission.

There is no `sorry` in this file.

Counts for this run are in `Autoform/SpecsGen/report.json`.
-/

def dom_conform_add : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (11), Val.int (7)] }, expected := EResult.val (Val.int (18)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (14), Val.int (19)] }, expected := EResult.val (Val.int (33)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-11), Val.int (0)] }, expected := EResult.val (Val.int (-11)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (6), Val.int (-9)] }, expected := EResult.val (Val.int (-3)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_add : ∀ fuel, FUEL ≤ fuel → ((dom_conform_add).all (lawConform C fuel f_add)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_add).all (lawConform C 8 f_add) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_add) (lawConform C 8 f_add) (lawConform C fuel f_add)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_bump : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (16)] }, expected := EResult.val (Val.int (17)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (254)] }, expected := EResult.val (Val.int (255)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (7)] }, expected := EResult.val (Val.int (8)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (19)] }, expected := EResult.val (Val.int (20)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_bump : ∀ fuel, FUEL ≤ fuel → ((dom_conform_bump).all (lawConform C fuel f_bump)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_bump).all (lawConform C 8 f_bump) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_bump) (lawConform C 8 f_bump) (lawConform C fuel f_bump)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_hexliteral : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [] }, expected := EResult.val (Val.int (4294967295)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_hexliteral : ∀ fuel, FUEL ≤ fuel → ((dom_conform_hexliteral).all (lawConform C fuel f_hexliteral)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_hexliteral).all (lawConform C 8 f_hexliteral) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_hexliteral) (lawConform C 8 f_hexliteral) (lawConform C fuel f_hexliteral)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_literal : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [] }, expected := EResult.val (Val.int (2147483649)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_literal : ∀ fuel, FUEL ≤ fuel → ((dom_conform_literal).all (lawConform C fuel f_literal)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_literal).all (lawConform C 8 f_literal) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_literal) (lawConform C 8 f_literal) (lawConform C fuel f_literal)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_mixed : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-18), Val.int (4294967277)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (17), Val.int (4294967288)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (16), Val.int (4294967293)] }, expected := EResult.val (Val.int (1)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-16), Val.int (6)] }, expected := EResult.val (Val.int (0)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_mixed : ∀ fuel, FUEL ≤ fuel → ((dom_conform_mixed).all (lawConform C fuel f_mixed)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_mixed).all (lawConform C 8 f_mixed) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_mixed) (lawConform C 8 f_mixed) (lawConform C fuel f_mixed)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_mixedwidth : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (3), Val.int (12)] }, expected := EResult.val (Val.int (15)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (2), Val.int (8)] }, expected := EResult.val (Val.int (10)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-6), Val.int (15)] }, expected := EResult.val (Val.int (9)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (16), Val.int (4294967276)] }, expected := EResult.val (Val.int (4294967292)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_mixedwidth : ∀ fuel, FUEL ≤ fuel → ((dom_conform_mixedwidth).all (lawConform C fuel f_mixedwidth)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_mixedwidth).all (lawConform C 8 f_mixedwidth) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_mixedwidth) (lawConform C 8 f_mixedwidth) (lawConform C fuel f_mixedwidth)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_nested : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-4), Val.int (-12)] }, expected := EResult.val (Val.int (192)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (-3), Val.int (5)] }, expected := EResult.val (Val.int (10)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (19), Val.int (-15)] }, expected := EResult.val (Val.int (-60)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (9), Val.int (-5)] }, expected := EResult.val (Val.int (-20)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_nested : ∀ fuel, FUEL ≤ fuel → ((dom_conform_nested).all (lawConform C fuel f_nested)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_nested).all (lawConform C 8 f_nested) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_nested) (lawConform C 8 f_nested) (lawConform C fuel f_nested)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_octalcompare : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [] }, expected := EResult.val (Val.int (0)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_octalcompare : ∀ fuel, FUEL ≤ fuel → ((dom_conform_octalcompare).all (lawConform C fuel f_octalcompare)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_octalcompare).all (lawConform C 8 f_octalcompare) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_octalcompare) (lawConform C 8 f_octalcompare) (lawConform C fuel f_octalcompare)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_promote : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (241), Val.int (3)] }, expected := EResult.val (Val.int (244)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (250), Val.int (14)] }, expected := EResult.val (Val.int (264)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (236), Val.int (3)] }, expected := EResult.val (Val.int (239)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (15), Val.int (2)] }, expected := EResult.val (Val.int (17)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_promote : ∀ fuel, FUEL ≤ fuel → ((dom_conform_promote).all (lawConform C fuel f_promote)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_promote).all (lawConform C 8 f_promote) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_promote) (lawConform C 8 f_promote) (lawConform C fuel f_promote)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_right : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (4294967295), Val.int (14)] }, expected := EResult.val (Val.int (262143)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_right : ∀ fuel, FUEL ≤ fuel → ((dom_conform_right).all (lawConform C fuel f_right)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_right).all (lawConform C 8 f_right) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_right) (lawConform C 8 f_right) (lawConform C fuel f_right)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_wideshift : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [] }, expected := EResult.val (Val.int (1099511627776)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_wideshift : ∀ fuel, FUEL ≤ fuel → ((dom_conform_wideshift).all (lawConform C fuel f_wideshift)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_wideshift).all (lawConform C 8 f_wideshift) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_wideshift) (lawConform C 8 f_wideshift) (lawConform C fuel f_wideshift)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

def dom_conform_wrap : List Obs :=
  [{ case := { heap := h0 ++ [], self := none, args := [Val.int (0), Val.int (0)] }, expected := EResult.val (Val.int (0)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (4), Val.int (4294967280)] }, expected := EResult.val (Val.int (4294967284)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (4294967277), Val.int (4294967283)] }, expected := EResult.val (Val.int (4294967264)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (4294967286), Val.int (15)] }, expected := EResult.val (Val.int (5)), post := none },
   { case := { heap := h0 ++ [], self := none, args := [Val.int (4294967295), Val.int (4294967293)] }, expected := EResult.val (Val.int (4294967292)), post := none }]

/-- Holds at **every** fuel budget at or above `FUEL`.

Checked at fuel 8 by computation, then transported by `applyFunc_fuel_mono_all`.
The `gRunObs` conjunct is the `≠ outOfFuel` side condition, evaluated over the same
domain rather than assumed: without it a law could hold at `FUEL` for the reason that
nothing ran. -/
theorem conform_wrap : ∀ fuel, FUEL ≤ fuel → ((dom_conform_wrap).all (lawConform C fuel f_wrap)) = true := by
  intro fuel hf
  have hk : 8 ≤ fuel := Nat.le_trans (by decide : 8 ≤ FUEL) hf
  have hchecked : (dom_conform_wrap).all (lawConform C 8 f_wrap) = true := by
    first | decide +kernel | fail "kernel computation did not establish the claim"
  exact all_transfer _ (gRunObs C 8 f_wrap) (lawConform C 8 f_wrap) (lawConform C fuel f_wrap)
    (fun c hgc hlc =>
      lawConform_fuel_mono_all (hk := hk) (hg := hgc) (h := hlc))
    (by first | decide +kernel | fail "kernel computation did not establish the claim") (hchecked)

/-- Everything this module states but does not prove. A `Prop`-valued `def` asserts nothing, so nothing here is admitted. -/
def obligations : List OpenObligation :=
  []

#eval IO.println (renderObligations "PipelineC" obligations)

/-! ## Anti-vacuity gate

`#audit_depends` fails the build if a theorem's proof term never mentions the generated definition it claims to be about — the necessary half of the gate. The sufficient half is `scripts/mutate.py`, run against this file. -/

#audit_depends conform_add on f_add
#audit_depends conform_bump on f_bump
#audit_depends conform_hexliteral on f_hexliteral
#audit_depends conform_literal on f_literal
#audit_depends conform_mixed on f_mixed
#audit_depends conform_mixedwidth on f_mixedwidth
#audit_depends conform_nested on f_nested
#audit_depends conform_octalcompare on f_octalcompare
#audit_depends conform_promote on f_promote
#audit_depends conform_right on f_right
#audit_depends conform_wideshift on f_wideshift
#audit_depends conform_wrap on f_wrap

/-! ## Axiom basis

`#audit_axioms` fails the build on `sorryAx`, `ofReduceBool` or `ofReduceNat`, so "no admitted step, no `native_decide`" is checked here rather than asserted in prose. -/

#audit_axioms conform_add
#audit_axioms conform_bump
#audit_axioms conform_hexliteral
#audit_axioms conform_literal
#audit_axioms conform_mixed
#audit_axioms conform_mixedwidth
#audit_axioms conform_nested
#audit_axioms conform_octalcompare
#audit_axioms conform_promote
#audit_axioms conform_right
#audit_axioms conform_wideshift
#audit_axioms conform_wrap

end Autoform.SpecsGen.PipelineC
