import Std

/-! Generated by `scripts/external_bases.py --emit-lean`. Do not edit by hand:
the Python file is the source of truth and `tests/test_external_bases.py` compares
the two. Contracts frozen from CPython 3.11; `scripts/differential.py` verifies each
against the live class before encoding a receiver whose MRO contains it. -/

namespace Autoform.Core

/-- What an external base contributes to a class namespace: the attribute names it
provides beyond `object` (each one a named hole when reached, because its code is
not translated) and the abstract methods a subclass must define to be instantiable. -/
structure ExternalBase where
  provides : List String
  abstract : List String
  deriving Repr, Inhabited, BEq

/-- The marker a contracted base carries in `ClassDecl.bases`: `<external>` and the
class's `module.qualname`. No source language can spell it. -/
def externalBasePrefix : String := "<external>"

def externalBaseContracts : List (String × ExternalBase) :=
  [("<external>collections.abc.AsyncGenerator",
   { provides := ["__abstractmethods__", "__aiter__", "__anext__", "__class_getitem__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl", "aclose", "asend", "athrow"],
     abstract := ["asend", "athrow"] }),
  ("<external>collections.abc.AsyncIterable",
   { provides := ["__abstractmethods__", "__aiter__", "__class_getitem__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__aiter__"] }),
  ("<external>collections.abc.AsyncIterator",
   { provides := ["__abstractmethods__", "__aiter__", "__anext__", "__class_getitem__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__anext__"] }),
  ("<external>collections.abc.Awaitable",
   { provides := ["__abstractmethods__", "__await__", "__class_getitem__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__await__"] }),
  ("<external>collections.abc.ByteString",
   { provides := ["__abstractmethods__", "__class_getitem__", "__contains__", "__doc__", "__getitem__", "__iter__", "__len__", "__module__", "__reversed__", "__slots__", "__subclasshook__", "_abc_impl", "count", "index"],
     abstract := ["__getitem__", "__len__"] }),
  ("<external>collections.abc.Callable",
   { provides := ["__abstractmethods__", "__call__", "__class_getitem__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__call__"] }),
  ("<external>collections.abc.Collection",
   { provides := ["__abstractmethods__", "__class_getitem__", "__contains__", "__doc__", "__iter__", "__len__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__contains__", "__iter__", "__len__"] }),
  ("<external>collections.abc.Container",
   { provides := ["__abstractmethods__", "__class_getitem__", "__contains__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__contains__"] }),
  ("<external>collections.abc.Coroutine",
   { provides := ["__abstractmethods__", "__await__", "__class_getitem__", "__doc__", "__module__", "__slots__", "__subclasshook__", "_abc_impl", "close", "send", "throw"],
     abstract := ["__await__", "send", "throw"] }),
  ("<external>collections.abc.Generator",
   { provides := ["__abstractmethods__", "__class_getitem__", "__doc__", "__iter__", "__module__", "__next__", "__slots__", "__subclasshook__", "_abc_impl", "close", "send", "throw"],
     abstract := ["send", "throw"] }),
  ("<external>collections.abc.Hashable",
   { provides := ["__abstractmethods__", "__doc__", "__hash__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__hash__"] }),
  ("<external>collections.abc.Iterable",
   { provides := ["__abstractmethods__", "__class_getitem__", "__doc__", "__iter__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__iter__"] }),
  ("<external>collections.abc.Iterator",
   { provides := ["__abstractmethods__", "__class_getitem__", "__doc__", "__iter__", "__module__", "__next__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__next__"] }),
  ("<external>collections.abc.Mapping",
   { provides := ["__abstractmethods__", "__class_getitem__", "__contains__", "__doc__", "__eq__", "__getitem__", "__hash__", "__iter__", "__len__", "__module__", "__reversed__", "__slots__", "__subclasshook__", "_abc_impl", "get", "items", "keys", "values"],
     abstract := ["__getitem__", "__iter__", "__len__"] }),
  ("<external>collections.abc.MutableMapping",
   { provides := ["_MutableMapping__marker", "__abstractmethods__", "__class_getitem__", "__contains__", "__delitem__", "__doc__", "__eq__", "__getitem__", "__hash__", "__iter__", "__len__", "__module__", "__reversed__", "__setitem__", "__slots__", "__subclasshook__", "_abc_impl", "clear", "get", "items", "keys", "pop", "popitem", "setdefault", "update", "values"],
     abstract := ["__delitem__", "__getitem__", "__iter__", "__len__", "__setitem__"] }),
  ("<external>collections.abc.MutableSequence",
   { provides := ["__abstractmethods__", "__class_getitem__", "__contains__", "__delitem__", "__doc__", "__getitem__", "__iadd__", "__iter__", "__len__", "__module__", "__reversed__", "__setitem__", "__slots__", "__subclasshook__", "_abc_impl", "append", "clear", "count", "extend", "index", "insert", "pop", "remove", "reverse"],
     abstract := ["__delitem__", "__getitem__", "__len__", "__setitem__", "insert"] }),
  ("<external>collections.abc.MutableSet",
   { provides := ["__abstractmethods__", "__and__", "__class_getitem__", "__contains__", "__doc__", "__eq__", "__ge__", "__gt__", "__hash__", "__iand__", "__ior__", "__isub__", "__iter__", "__ixor__", "__le__", "__len__", "__lt__", "__module__", "__or__", "__rand__", "__ror__", "__rsub__", "__rxor__", "__slots__", "__sub__", "__subclasshook__", "__xor__", "_abc_impl", "_from_iterable", "_hash", "add", "clear", "discard", "isdisjoint", "pop", "remove"],
     abstract := ["__contains__", "__iter__", "__len__", "add", "discard"] }),
  ("<external>collections.abc.Reversible",
   { provides := ["__abstractmethods__", "__class_getitem__", "__doc__", "__iter__", "__module__", "__reversed__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__iter__", "__reversed__"] }),
  ("<external>collections.abc.Sequence",
   { provides := ["__abstractmethods__", "__class_getitem__", "__contains__", "__doc__", "__getitem__", "__iter__", "__len__", "__module__", "__reversed__", "__slots__", "__subclasshook__", "_abc_impl", "count", "index"],
     abstract := ["__getitem__", "__len__"] }),
  ("<external>collections.abc.Set",
   { provides := ["__abstractmethods__", "__and__", "__class_getitem__", "__contains__", "__doc__", "__eq__", "__ge__", "__gt__", "__hash__", "__iter__", "__le__", "__len__", "__lt__", "__module__", "__or__", "__rand__", "__ror__", "__rsub__", "__rxor__", "__slots__", "__sub__", "__subclasshook__", "__xor__", "_abc_impl", "_from_iterable", "_hash", "isdisjoint"],
     abstract := ["__contains__", "__iter__", "__len__"] }),
  ("<external>collections.abc.Sized",
   { provides := ["__abstractmethods__", "__doc__", "__len__", "__module__", "__slots__", "__subclasshook__", "_abc_impl"],
     abstract := ["__len__"] })]

/-- The contract of a base name, if it is a contracted external base. Exact key
match on the marker, so the kernel decides it without any prefix test. -/
def externalContract (name : String) : Option ExternalBase :=
  (externalBaseContracts.find? (·.1 == name)).map Prod.snd

end Autoform.Core
