"""An autonomous proving agent in a loop with Lean (Gauss-style), outside the trusted base.

A job is one theorem: the file text up to it (imports, definitions, helper lemmas), its
statement, and a natural-language blueprint. An agent (headless Claude Code) works on a
private job directory with a Lean runtime, running `./check.sh FILE` (a wrapper around
`lake env lean` from the Lean root) until the file checks. It returns a proof; the agent's
report is never trusted.

Acceptance is independent of the agent:
  * the proof is spliced under the ORIGINAL statement, recovered from the job, so an agent
    that edited the statement proves nothing;
  * proof and helpers are screened for forbidden constructs (comments and string literals
    removed first, so a comment that mentions `sorry` is harmless);
  * the file is re-elaborated from scratch;
  * `#print axioms` must list only propext / Classical.choice / Quot.sound
    (no sorryAx, no Lean.ofReduceBool from native_decide, no new axiom).

Confinement (defence in depth, not part of the trust argument):
  * the agent may use only `./check.sh`, Read, Edit, Write, Grep and Glob, from its job dir;
    `check.sh` refuses files outside the job dir and files that run code at elaboration;
  * the Lean root's git state is snapshotted before and after each agent run; any tracked
    file the agent changed is restored and reported;
  * a timed-out agent is killed with its whole process group (its Lean children too);
  * every agent exchange is saved to the job dir (`*.transcript.*`).

Accepted proofs are cached by sha256(prefix + statement + lean-toolchain + lake-manifest);
a cache hit is re-checked by the kernel, never trusted. A shared `Budget` caps total spend.
"""
from __future__ import annotations

import concurrent.futures as futures
import hashlib
import json
import os
import re
import shlex
import shutil
import signal
import subprocess
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

ALLOWED_AXIOMS = {'propext', 'Classical.choice', 'Quot.sound'}
# Screened on proof + helpers after comments and string literals are removed.
FORBIDDEN = re.compile(
    r'(?<![\w.])(sorry|admit|native_decide|axiom|implemented_by|extern|unsafe|opaque|'
    r'run_cmd|run_elab|run_meta|run_tac|elab|elab_rules|macro|macro_rules|syntax|'
    r'initialize|builtin_initialize|skipKernelTC|debug\.[\w.]*)(?![\w])'
    r'|#eval|#exit|#guard_msgs|@\[\s*(extern|implemented_by|csimp)')
ALLOWED_TOOLS = 'Bash(./check.sh:*),Read,Edit,Write,Grep,Glob'
# check.sh refuses files that execute code while elaborating.
CHECK_REFUSE = r'#eval|run_cmd|run_elab|run_meta|IO\.Process|IO\.FS|initialize|unsafe'

PROMPT = """You are a Lean 4 proof engineer working autonomously. Prove ONE theorem.

File (already contains the theorem, with `sorry` as its proof): ./{file}
Theorem: `{name}`
Check your work with:  ./check.sh {file}
(check.sh runs `lake env lean` with this project's library, Lean {toolchain}; ~10-60 s.
It only accepts files in this directory. You have no other shell access.)

Blueprint (what the statement means and why it should hold):
{blueprint}

Rules:
- Replace only the `sorry` of `{name}`. Do not change its statement, its name, or any
  other declaration's statement. You MAY add helper lemmas immediately before it.
- Forbidden anywhere: sorry, admit, native_decide, axiom, implemented_by, extern, unsafe,
  #eval, run_cmd, elab/macro/syntax definitions, debug options.
- The kernel must accept it: finish only when `./check.sh {file}` reports no errors for
  `{name}` and `#print axioms {name}` (append it temporarily if useful) lists at most
  propext, Classical.choice, Quot.sound.
- Useful tactics here: `simp [...]`, `decide`, `omega`, `rfl`, `with_unfolding_all rfl`,
  `split`, `cases`, `induction`; the file may define `af_eval`, which head-normalizes
  interpreter applications (`runFunc ...`) by unfolding and iota-reduction.
- Work for as long as needed; try several strategies if one fails.

When done, print the final helper lemmas (if any) and the proof as:
<helpers>
...lean declarations or empty...
</helpers>
<proof>
by
  ...
</proof>
If you cannot prove it, print <proof>FAILED</proof> and a one-paragraph reason in <reason></reason>.
"""

CHECK_SH = """#!/bin/sh
# Generated by autoform's prover: the agent's only way to run Lean.
[ $# -eq 1 ] || {{ echo "usage: ./check.sh FILE.lean" >&2; exit 2; }}
job={job}
case "$1" in /*) f="$1" ;; *) f="$job/$1" ;; esac
d=$(cd "$(dirname "$f")" 2>/dev/null && pwd -P) || {{ echo "check.sh: no such file: $1" >&2; exit 2; }}
f="$d/$(basename "$f")"
case "$d" in "$job"|"$job"/*) ;; *) echo "check.sh: only files under $job may be checked" >&2; exit 2 ;; esac
[ -f "$f" ] || {{ echo "check.sh: no such file: $1" >&2; exit 2; }}
if grep -nE {refuse} "$f"; then echo "check.sh: refused: the file runs code at elaboration time" >&2; exit 2; fi
PATH={elan}:$PATH
export PATH
cd {root} && exec lake env lean "$f"
"""


@dataclass
class Job:
    name: str                 # theorem name as written in the file (unqualified)
    prefix: str               # file text before the theorem
    statement: str            # `theorem name ... :` up to `:=` (exclusive)
    blueprint: str = ''
    suffix: str = ''          # text after the theorem (usually empty)

    def file_text(self, proof: str, helpers: str = '') -> str:
        body = self.prefix.rstrip() + '\n\n'
        if helpers.strip():
            body += helpers.strip() + '\n\n'
        return body + self.statement.rstrip() + ' :=\n' + proof.strip() + '\n' + self.suffix


@dataclass
class Result:
    name: str
    status: str               # PROVED | FAILED | TIMEOUT | BUDGET | ERROR
    proof: str = ''
    helpers: str = ''
    reason: str = ''
    axioms: list = field(default_factory=list)
    seconds: float = 0.0
    cost_usd: float = 0.0
    certificate: str | None = None
    certificate_sha256: str | None = None
    cached: bool = False
    restored: list = field(default_factory=list)    # tracked files of the Lean root the agent changed
    untracked: list = field(default_factory=list)   # new untracked files it left there (reported only)
    transcripts: list = field(default_factory=list)


class Budget:
    """Total spend cap shared by concurrent jobs. Checked before each agent call, so
    calls already in flight may overshoot by at most one call per worker."""

    def __init__(self, limit_usd: float | None = None):
        self.limit, self.spent, self._lock = limit_usd, 0.0, threading.Lock()

    def exhausted(self) -> bool:
        with self._lock:
            return self.limit is not None and self.spent >= self.limit

    def charge(self, usd: float):
        with self._lock:
            self.spent += float(usd or 0)


# --- Lean text scanning -------------------------------------------------------------------

def strip_comments_and_strings(text: str) -> str:
    """Lean text with `--` / nested `/- -/` comments and string literals blanked out."""
    out, i, n = [], 0, len(text)
    while i < n:
        if text.startswith('--', i):
            j = text.find('\n', i)
            i = n if j < 0 else j
        elif text.startswith('/-', i):
            depth, i = 1, i + 2
            while i < n and depth:
                if text.startswith('/-', i):
                    depth, i = depth + 1, i + 2
                elif text.startswith('-/', i):
                    depth, i = depth - 1, i + 2
                else:
                    i += 1
            out.append(' ')
        elif text[i] == '"':
            i += 1
            while i < n and text[i] != '"':
                i += 2 if text[i] == '\\' else 1
            i += 1
            out.append('""')
        else:
            out.append(text[i])
            i += 1
    return ''.join(out)


def forbidden(text: str) -> str | None:
    m = FORBIDDEN.search(strip_comments_and_strings(text))
    return m.group(0) if m else None


_OPEN, _CLOSE = '([{⟨⦃⟦', ')]}⟩⦄⟧'
_BINDS = re.compile(r'(let|have)(?![\w\'])')


def split_decl(chunk: str) -> tuple[str, str] | None:
    """Split `theorem n ... : T := proof` at the `:=` that starts the proof: the first one
    at bracket depth 0, outside comments and strings, not owed to a `let`/`have` in the
    statement. Returns (statement, proof) or None."""
    depth, pending, i, n = 0, 0, 0, len(chunk)
    while i < n:
        c = chunk[i]
        if chunk.startswith('--', i):
            j = chunk.find('\n', i)
            i = n if j < 0 else j
            continue
        if chunk.startswith('/-', i):
            d, i = 1, i + 2
            while i < n and d:
                if chunk.startswith('/-', i):
                    d, i = d + 1, i + 2
                elif chunk.startswith('-/', i):
                    d, i = d - 1, i + 2
                else:
                    i += 1
            continue
        if c == '"':
            i += 1
            while i < n and chunk[i] != '"':
                i += 2 if chunk[i] == '\\' else 1
            i += 1
            continue
        if c in _OPEN:
            depth += 1
        elif c in _CLOSE:
            depth = max(0, depth - 1)
        elif depth == 0:
            if chunk.startswith(':=', i):
                if pending:
                    pending -= 1
                else:
                    return chunk[:i], chunk[i + 2:]
                i += 2
                continue
            m = _BINDS.match(chunk, i)
            if m and (i == 0 or not (chunk[i - 1].isalnum() or chunk[i - 1] in "_.'")):
                pending += 1
                i = m.end()
                continue
        i += 1
    return None


# --- running processes -------------------------------------------------------------------

def _lean_env() -> dict:
    return dict(os.environ, PATH=str(Path.home() / '.elan/bin') + os.pathsep + os.environ.get('PATH', ''))


def run_group(cmd, cwd, env=None, timeout=None) -> tuple[int, str, str]:
    """Run in a new session; on timeout kill the whole process group and re-raise."""
    proc = subprocess.Popen(cmd, cwd=str(cwd), env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            text=True, start_new_session=True)
    try:
        out, err = proc.communicate(timeout=timeout)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        proc.communicate()
        raise
    return proc.returncode, out, err


def lean_check(root: Path, path: Path, name: str, timeout: int = 1800) -> tuple[bool, list, str]:
    """Elaborate `path` and read `#print axioms name`; True iff clean and standard-only."""
    text = path.read_text()
    probe = path.with_suffix('.check.lean')
    probe.write_text(text + f'\n#print axioms {name}\n')
    try:
        code, so, se = run_group(['lake', 'env', 'lean', str(probe)], root, _lean_env(), timeout)
    except subprocess.TimeoutExpired:
        return False, [], 'lean timeout'
    out = so + se
    m = re.search(rf"'[^']*{re.escape(name)}' depends on axioms: \[([^\]]*)\]", out)
    axioms = [a.strip() for a in m.group(1).split(',')] if m else []
    if re.search(rf"'[^']*{re.escape(name)}' does not depend on any axioms", out):
        axioms, m = [], True
    errors = [l for l in out.splitlines() if ': error' in l]
    ok = code == 0 and not errors and bool(m) and set(axioms) <= ALLOWED_AXIOMS
    return ok, axioms, '\n'.join(errors[:20]) or out[-2000:]


def _extract(tag: str, text: str) -> str | None:
    found = re.findall(rf'<{tag}>\s*(.*?)\s*</{tag}>', text, re.S)
    return found[-1] if found else None


class ClaudeCodeAgent:
    """Headless Claude Code with Lean access only through ./check.sh in its job dir."""
    name = 'claude-code'

    def __init__(self, model: str | None = None, max_turns: int = 60, timeout: int = 3600):
        self.model, self.max_turns, self.timeout = model, max_turns, timeout
        if not shutil.which('claude'):
            raise RuntimeError('claude CLI not found on PATH')

    def run(self, prompt: str, cwd: Path) -> tuple[str, float]:
        cmd = ['claude', '-p', prompt, '--output-format', 'stream-json', '--verbose',
               '--max-turns', str(self.max_turns), '--allowedTools', ALLOWED_TOOLS,
               '--permission-mode', 'acceptEdits']
        if self.model:
            cmd += ['--model', self.model]
        env = {k: v for k, v in os.environ.items() if k != 'ANTHROPIC_API_KEY'}  # use the logged-in plan
        _, out, err = run_group(cmd, cwd, env, self.timeout)   # TimeoutExpired propagates
        stamp = time.strftime('%Y%m%d-%H%M%S') + f'-{os.getpid()}-{threading.get_ident() % 100000}'
        (Path(cwd) / f'agent-{stamp}.transcript.jsonl').write_text(out + ('\n' + err if err else ''))
        text, cost = '', 0.0
        for line in out.splitlines():
            try:
                ev = json.loads(line)
            except ValueError:
                continue
            if isinstance(ev, dict) and ev.get('type') == 'result':
                text, cost = ev.get('result') or '', float(ev.get('total_cost_usd') or 0)
        return (text or out[-4000:] + err[-2000:]), cost


# --- confinement of the Lean root ----------------------------------------------------------

_SNAP_LOCK = threading.Lock()


def _git(root, *args) -> str | None:
    try:
        return subprocess.run(['git', *args], cwd=root, capture_output=True, text=True, timeout=120).stdout
    except (OSError, subprocess.TimeoutExpired):
        return None


def snapshot(root: Path) -> dict | None:
    """git porcelain status plus the contents of already-dirty tracked files."""
    status = _git(root, 'status', '--porcelain', '--untracked-files=all')
    if status is None or _git(root, 'rev-parse', '--is-inside-work-tree') is None:
        return None
    dirty, untracked = {}, set()
    for line in status.splitlines():
        path = line[3:].split(' -> ')[-1].strip('"')
        if line.startswith('??'):
            untracked.add(path)
            continue
        f = Path(root) / path
        dirty[path] = f.read_bytes() if f.is_file() else None
    return {'status': status, 'dirty': dirty, 'untracked': untracked}


def restore(root: Path, before: dict | None) -> tuple[list, list]:
    """Undo agent changes to tracked files; return (restored, new_untracked)."""
    after = snapshot(root)
    if before is None or after is None:
        return [], []
    restored = []
    for path, content in after['dirty'].items():
        if path in before['dirty']:
            if content != before['dirty'][path]:
                old = before['dirty'][path]
                f = Path(root) / path
                if old is None:
                    f.unlink(missing_ok=True)
                else:
                    f.parent.mkdir(parents=True, exist_ok=True)
                    f.write_bytes(old)
                restored.append(path)
        else:
            _git(root, 'checkout', 'HEAD', '--', path)
            restored.append(path)
    for path, content in before['dirty'].items():   # dirty before, cleaned by the agent
        if path not in after['dirty'] and content is not None:
            (Path(root) / path).write_bytes(content)
            restored.append(path)
    return sorted(set(restored)), sorted(after['untracked'] - before['untracked'])


# --- proof cache ------------------------------------------------------------------------

def cache_key(job: Job, root: Path) -> str:
    h = hashlib.sha256()
    for part in (job.prefix, job.statement):
        h.update(part.encode() + b'\0')
    for name in ('lean-toolchain', 'lake-manifest.json'):
        f = Path(root) / name
        h.update(f.read_bytes() if f.is_file() else b'-')
        h.update(b'\0')
    return h.hexdigest()


def _cache_get(cache_dir, key):
    f = Path(cache_dir) / f'{key}.json' if cache_dir else None
    if f and f.is_file():
        try:
            return json.loads(f.read_text())
        except ValueError:
            return None
    return None


def _cache_put(cache_dir, key, proof, helpers):
    if cache_dir:
        Path(cache_dir).mkdir(parents=True, exist_ok=True)
        (Path(cache_dir) / f'{key}.json').write_text(json.dumps({'proof': proof, 'helpers': helpers}))


# --- the loop ----------------------------------------------------------------------------

def _accept(job, root, workdir, proof, helpers, started, cost, **extra) -> tuple[Result | None, str]:
    bad = forbidden(proof) or forbidden(helpers)
    if bad:
        return None, f'proof or helpers contain a forbidden construct: {bad}'
    final = workdir / f'{job.name}.final.lean'
    final.write_text(job.file_text(proof, helpers))
    ok, axioms, detail = lean_check(root, final, job.name)
    if not ok:
        return None, 'independent check failed:\n' + detail
    return Result(job.name, 'PROVED', proof, helpers, axioms=axioms, seconds=round(time.time() - started, 1),
                  cost_usd=round(cost, 4), certificate=str(final),
                  certificate_sha256=hashlib.sha256(final.read_bytes()).hexdigest(), **extra), ''


def write_check_sh(workdir: Path, root: Path) -> Path:
    f = workdir / 'check.sh'
    f.write_text(CHECK_SH.format(job=shlex.quote(str(workdir)), root=shlex.quote(str(root)),
                                 elan=shlex.quote(str(Path.home() / '.elan/bin')),
                                 refuse=shlex.quote(CHECK_REFUSE)))
    f.chmod(0o755)
    return f


def prove(job: Job, root: Path, workdir: Path, agent=None, attempts: int = 2, *, cache_dir=None,
          budget: Budget | None = None) -> Result:
    root, workdir = Path(root).resolve(), Path(workdir).resolve()
    workdir.mkdir(parents=True, exist_ok=True)
    started, cost, reason = time.time(), 0.0, ''
    key = cache_key(job, root)
    hit = _cache_get(cache_dir, key)
    if hit:
        res, why = _accept(job, root, workdir, hit.get('proof', ''), hit.get('helpers', ''), started, 0.0,
                           cached=True)
        if res:
            return res
        reason = 'cached proof no longer checks: ' + why
    write_check_sh(workdir, root)
    toolchain = (root / 'lean-toolchain').read_text().strip() if (root / 'lean-toolchain').exists() else '?'
    restored, untracked, transcripts, status = [], [], [], 'FAILED'
    for attempt in range(1, attempts + 1):
        if budget is not None and budget.exhausted():
            status, reason = 'BUDGET', (reason + '\n' if reason else '') + 'budget exhausted before attempt %d' % attempt
            break
        if agent is None:
            try:
                agent = ClaudeCodeAgent()
            except RuntimeError as exc:
                status, reason = 'ERROR', str(exc)
                break
        fname = f'{job.name}.attempt{attempt}.lean'
        (workdir / fname).write_text(job.file_text('by\n  sorry'))
        prompt = PROMPT.format(file=fname, name=job.name, toolchain=toolchain,
                               blueprint=job.blueprint or '(none supplied)')
        if reason:
            prompt += f'\n\nA previous attempt failed independent checking:\n{reason[:3000]}\n'
        before = snapshot(root)
        t0, reply, c = time.time(), '', 0.0
        try:
            reply, c = agent.run(prompt, workdir)
            status = 'FAILED'
        except subprocess.TimeoutExpired:
            status, reason = 'TIMEOUT', 'agent timed out (process group killed)'
        except Exception as exc:  # an agent crash is a failed attempt, not a crashed run
            status, reason = 'ERROR', f'agent error: {exc}'
        finally:
            with _SNAP_LOCK:
                r, u = restore(root, before)
            restored += r
            untracked += u
        cost += c
        if budget is not None:
            budget.charge(c)
        tr = workdir / f'{job.name}.attempt{attempt}.transcript.json'
        tr.write_text(json.dumps({'agent': getattr(agent, 'name', type(agent).__name__), 'prompt': prompt,
                                  'reply': reply, 'cost_usd': c, 'seconds': round(time.time() - t0, 1),
                                  'restored': r, 'untracked': u}, indent=1))
        transcripts.append(str(tr))
        if status in ('TIMEOUT', 'ERROR'):
            continue
        if r:
            reason = f'agent modified tracked files of the Lean root (restored): {r}'
            continue
        proof = _extract('proof', reply)
        helpers = _extract('helpers', reply) or ''
        if not proof or proof.strip() == 'FAILED':
            reason = _extract('reason', reply) or 'agent reported failure'
            continue
        res, reason = _accept(job, root, workdir, proof, helpers, started, cost, restored=sorted(set(restored)),
                              untracked=sorted(set(untracked)), transcripts=transcripts)
        if res:
            _cache_put(cache_dir, key, proof, helpers)
            return res
        status = 'FAILED'
    return Result(job.name, status, reason=reason, seconds=round(time.time() - started, 1), cost_usd=round(cost, 4),
                  restored=sorted(set(restored)), untracked=sorted(set(untracked)), transcripts=transcripts)


def prove_many(jobs: list, root: Path, workdir: Path, parallel: int = 3, budget_usd: float | None = None,
               **kw) -> list:
    """Bounded concurrency: every agent runs its own Lean processes (a few GB each)."""
    kw.setdefault('budget', Budget(budget_usd))
    with futures.ThreadPoolExecutor(max_workers=max(1, parallel)) as pool:
        return list(pool.map(lambda j: prove(j, root, Path(workdir) / j.name, **kw), jobs))


# --- turning `sorry`s in a Lean file into jobs ------------------------------------------

DECL = re.compile(r'^(?:@\[[^\]]*\]\s*)?(?:private\s+|protected\s+)?(theorem|lemma)\s+(\S+)', re.M)


def jobs_from_file(path: Path, names: list | None = None) -> list:
    """Every theorem in `path` whose proof is `sorry` (or named explicitly), as a job whose
    prefix is the file up to that theorem. Helper lemmas added by one agent stay private
    to its job."""
    text = Path(path).read_text()
    starts = [(m.start(), m.group(2)) for m in DECL.finditer(text)]
    jobs = []
    for i, (start, name) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(text)
        parts = split_decl(text[start:end])
        if not parts:
            continue
        stmt, proof = parts
        first = strip_comments_and_strings(proof).split('\n\n')[0]
        wanted = (names and name in names) or (not names and re.fullmatch(r'\s*(by\s+)?sorry\s*', first))
        if not wanted:
            continue
        doc = re.findall(r'/--(.*?)-/\s*$', text[:start], re.S)
        jobs.append(Job(name=name, prefix=text[:start], statement=stmt, blueprint=(doc[-1].strip() if doc else '')))
    return jobs
